### ISSUE TITLE
Are relations important for the OSM network tool?

### ISSUE THREAD

**Issue by tuffzinator** [Esri/arcgis-osm-editor#100]
I have a question regarding the importance of relations of a .osm file for the generation of a networkDataset.
I have a .osm file and delete the unimportant ways via osmosis. When loading the OSM-file to ArcGIS, the process of "loading relations" is by far the longest part. What would happen to the networkDataset, which i would create afterwards, if i reject the relations in osmosis? are they necessary for the tool?

thanks in advance

**Comment by ThomasEmge** [comment]
Relations are important to a network as they contain the turning restrictions which are (or can be) incorporated into the network dataset.
Relations do take longer to load as the tool needs to figure out what the relation represents - a line or a polygon amongst other things and it does take a little bit of digging to do so.
