### ISSUE TITLE
Minor issue with the "Resolving multi-part geometries" progress display

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#101]
Hi Thomas,

I noticed a minor issue with the progress display during the "Resolving multi-part geometries" step of the **Load OSM File** tool. As you can see in the attached image, the display of the number of relations is stuck on 50.000, even though the progress bar continues and the process seems to go well.

I suspect this may have something to do with the large dataset being imported. It is the largest extract that I have imported up to now (and that successfully went past the node indexing stage), the DACh (Germany, Austria, Swizterland) extract of Geofabrik, as I am quite sure that I didn't see this on any smaller extract, where the display would always go like 50.000 ... 100.000 ... 150.000 etc.

![issue_resolving_multi-part_geometries_progress_display](https://cloud.githubusercontent.com/assets/7635726/11118296/1f2958e4-8941-11e5-91ad-80cd79bcd5ed.png)

**Comment by ThomasEmge** [comment]
Looks like a bug. Haven't noticed it either, I'll check it out.

**Comment by mboeringa** [comment]
Yes, it may be a minor issue with the setting of the progress. I'll let you know if the **Load OSM File** does properly finishes, which I suspect it will. The progress bar is properly updating, so I guess there is no real issue with the processing of the relations itself, but I can't tell for sure until it finishes and I see the resulting datasets.

**Comment by mboeringa** [comment]
@ThomasEmge, you may actually already have figured this out and fixed the issue, but I thought I would share this latest image, as it may help debugging. As you can see, there are now some other values being displayed...

![issue_resolving_multi-part_geometries_progress_display_2](https://cloud.githubusercontent.com/assets/7635726/11152800/f6cc986c-8a34-11e5-8063-f312ece1a496.png)

**Comment by ThomasEmge** [comment]
The current counting scheme is not correct and we should probably remove these messages altogether. For larger datasets the amount of messages is getting unwieldy and the messages themselves are not really adding any value. We can keep the progress indicator but skip the messages.

**Comment by mboeringa** [comment]
> We can keep the progress indicator but skip the messages.

Seems acceptable. As an alternative option or solution, instead of messages in the processing history, you might also consider displaying the same (but correct) information as part of the tools status message:

E.g.: **Loading relations, 50.000 processed...**

and update this single line in the tool with each step. This information will then only be available when it is needed, during the actual processing, and won't clutter up the processing history.

**Comment by mboeringa** [comment]
Last remark: my DACh (Germany, Austria, Switzerland) import successfully finished after about three weeks. I have now started a renderer session using my ArcGIS Renderer.

@ThomasEmge: if you decide to remove the messages, and keep the progress bar (*which is an absolute necessity in my opinion*, you can't have processes this long not giving feedback and the application appearing stalled), it still would be desirable to fix the progress code for the loading of the relations, because the progress isn't accurate. Instead of going from 0-100%, my DACh import went up to 30% on the progress bar, then declaring it was finished and showing the final report. I have seen this before, and actually I think with all imports.

Anyway, if, due to some technical reasons, it is not possible or easy to give an accurate progress on the relations processing, then keep the current implementation. It at least gives an idea of the progress, and it finishing earlier than expected, is better than no progress showing at all.
