### ISSUE TITLE
I cannot download and symbolize data

### ISSUE THREAD

**Issue by brkhnbkr** [Esri/arcgis-osm-editor#102]
Hello.

I'm using ArcGIS 10.2.2 ( version: 10.2.2.3552 ) with x64 geoprocessing. I downloaded and installed OSM Toolbox without a problem. 

But when I open a basemap (openstreet map) and click on "Download, Extract and Symbolize OSM Data"  the whole program freezes and I had to force close it every time I tried. Other features seems working though, I couldn't test all because I don't have enough knowledge about what they do and how they work since I just started to use ArcGIS couple days ago. I tried to uninstall x64 geoprocessing + install 32bit version of OSM Toolbox but nothing changed, still ArcMap collapses when I click on that feature. Can someone help me about this please ?

**Comment by brkhnbkr** [comment]
I reinstalled it but still same. I open Openstreet Maps as a basemap, click on "Download, Extract and Symbolize OSM Data" and the whole program stops working. 

Toolbox installed itself under Program Files(x86)/ESRI but its main directory is under Program Files(x86)/ArcGIS. Am I getting this error because of this ?  I tried to install it in different directories but nothing is working. Please help

**Comment by leaflifelayf** [comment]
Try to put your map into Geographic WGS 1984, I know that this tool does not require it, but it worked for me... maybe it will work for you.

**Comment by brkhnbkr** [comment]
Thanks for the reply !  I'm using "Add Basemap" tool in the program so I don't think that I can change it ?

**Comment by brkhnbkr** [comment]
I'm still waiting help ..

**Comment by ThomasEmge** [comment]
Please try to run the geoprocessing tools in the foreground. In ArcMap on the menus go to Geoprocessing > Geoprocessing Options... and in the dialog that opens uncheck the box in the Background Processing section called Enabled. 
Try to run the tool again and let me know what happens.

**Comment by ThomasEmge** [comment]
Please feel free to re-open this issue if you still run into problems.
