### ISSUE TITLE
"Add OSM Editor Extension" tool - apply to OSM feature dataset instead of feature class

### ISSUE THREAD

**Issue by eggwhites** [Esri/arcgis-osm-editor#103]
As of version 10.2.2 and 10.3.1., the "Add OSM Editor Extension" tool should be run before Editing downloaded OSM data. However, if you run the tool only on say, the polygon feature class, your uploaded data will not come through correctly. Likely because our feature dataset constructs the polygons from nodes and ways.

So currently, a user must run the tool three times - once on each layer - if they want to edit polygons (and likely lines too). Can we support running the tool once, and having it apply to all three feature classes? Or, have the tool dialog include browsing to each, like the Symbolize OSM Data model does?

**Comment by ThomasEmge** [comment]
A model tool seems the way to go.

**Comment by ThomasEmge** [comment]
or use these lines:

```Python
# Load the OSM Toolbox
arcpy.ImportToolbox(r'C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcToolbox\Toolboxes\OpenStreetMap Toolbox.tbx')
# assign the feature dataset as the current workspace
arcpy.env.workspace = r'D:\temp\osmtesting\onemore.gdb\liechtenstein3'
# list all feature classes in the workspace
fc_names = arcpy.ListFeatureClasses()
# for each feature class assign the extension
for name in fc_names:
    arcpy.OSMGPAddExtension_osmtools(arcpy.os.path.join(arcpy.env.workspace,name))
```
