### ISSUE TITLE
Cannot edit certain street line segments individually

### ISSUE THREAD

**Issue by NeilLoehlein** [Esri/arcgis-osm-editor#105]
I'm having difficulty finding a way to edit some of the line segments in the OSM street network that I downloaded. For these particular line segments, the attribute window does not show the editable attributes when I select a single line segment. I actually have to select multiple segments of these particular records to get the editable attributes to show up. These are the majority of the line segments that I'd like to edit, which makes editing the dataset difficult. It seems to be related with the type of street, or 'highway', that they are designated. All 'footways' and 'service' lines show the editable attributes when I select a single record. However, only a small minority of 'residential' streets will allow me to see and edit the attributes when one record is selected. I could not find one instance where 'Tertiary,' 'Secondary,' and 'Primary' streets displayed editable attributes when I selected one record. Has anyone experienced this issue before and found a way to work around it? 

thank you, 
Neil

**Comment by ThomasEmge** [comment]
Hmm, by attribute window you are referring to the attribute window of the editor as outlined in the online editing documentation https://desktop.arcgis.com/en/desktop/latest/manage-data/editing/a-quick-tour-of-editing.htm#ESRI_SECTION1_6967BD2F3090445C845B050E743D3AE5 correct?
Can you provide the OpenStreetMap  way ID or the geographic area you are working in so we can try to reproduce the issue?

**Comment by NeilLoehlein** [comment]
Yes, the attribute window that I'm referring to is the same in the documentation that the link describes. Here are some of the OSM IDs of the ways that I'm working with (which are in Portland, OR, btw):
OSM IDs of ways that do not display attributes in attribute window during editing session:
306057799
5525991
5519728
OSM IDs of ways that display attribute in attribute window during editing session: 
189899216
5527530
189899181

Thanks for checking it out!
Neil

**Comment by ThomasEmge** [comment]
Our interpretation of the *maxspeed* tag is causing the issue. Please go to the OSMFeaturesProperties.xml file and look for 

```xml
<tagkey name="maxspeed" tagtype="tag_double" displayname="Maximum Speed" infoURL="http://wiki.openstreetmap.org/wiki/Key:maxspeed"/>
```
and change it to 

```xml
<tagkey name="maxspeed" tagtype="tag_string" displayname="Maximum Speed" infoURL="http://wiki.openstreetmap.org/wiki/Key:maxspeed"/>
```
The speed tag contains more than just a number and causes the enumeration of attributes to fail. We will create an update for the file in the next release.

**Comment by NeilLoehlein** [comment]
Great, thanks for your help Thomas!

neil
