### ISSUE TITLE
Error when using Download OSM Data (XAPI) tool and Download, Extract and Symbolize tool just gets stuck

### ISSUE THREAD

**Issue by jcmlpt** [Esri/arcgis-osm-editor#106]
Hi,

I installed this tool and tried using it following the instructions here https://github.com/Esri/arcgis-osm-editor/wiki/Download-data-from-osm but I always get errors when trying.

Is this the right place to get help trying to understand what might be the problem?

Cheers

**Comment by ThomasEmge** [comment]
Yes, this is the right place. Both tools are giving are giving you problems and both are getting stuck? What types of errors are you encountering? Is the error the same for the Download OSM Data (XAPI) tool as Download OSM Data tool? If you do get errors in the geoprocessing messages please post them into this thread.
For right now I suggest that we keep the model tool "Download, Extract and Symbolize OSM Data" out of the troubleshooting process as it is a combination of multiple tools.

**Comment by jcmlpt** [comment]
Hi,

Using Download OSM Data (XAPI) tool I got errors twice. Using Download, Extract and Symbolize tool the window that opens gets stuck and unresponsive.

Screenshot of the error: (is the error also dumped somewhere with more info?)

![screenshot 4](https://cloud.githubusercontent.com/assets/15898420/11481877/b5361606-9797-11e5-8577-27afb679f676.png)

Thanks!

**Comment by ThomasEmge** [comment]
There are a number of issues with the tool as referenced here #80, #82, and #87.

Unless you have very specific reasons to use the XAPI interface I do suggest using the standard Download OSM Data tool (located just above the XAPI tool in the toolbox). The standard tool uses the central OpenStreetMap server which is most up-to-date data repository.

**Comment by jcmlpt** [comment]
Hi again,

I was just using the XAPI because it's in the first link in the How To guides (like the Download, Extract and Symbolize tool that also failed). I'll try the standard tool. Thanks!

My goal was to get elevation for Lisbon but I was told that the resolution is 90m (which is not detailed enough). Is this true?

**Comment by ThomasEmge** [comment]
I see, yeah XAPI is certainly not the tool you are looking for. In general, OpenStreetMap will give you vector data, like streets, building footprints, store locations, forests, administrative boundaries etc. with various additional information describing the information.

For elevation data please take a look at this service from ArcGIS Online http://www.arcgis.com/home/item.html?id=58a541efc59545e6b7137f961d7de883

For most of Europe you will find at least a 31 meters resolution.

**Comment by jcmlpt** [comment]
Thanks for the reply. I'll try creating my own DEM with some .dwg data I got, but that link will be helpful in the future for sure!
