### ISSUE TITLE
Cannot upload edited OSM data

### ISSUE THREAD

**Issue by NeilLoehlein** [Esri/arcgis-osm-editor#107]
When I split ways using the Split Tool on the standard ArcGIS Editor Toolbar, additional nodes associated with the split way are deleted for some reason (these deletions show up in the revision table, right after the creation of a node at the split). The node deletions keep me from being able to upload my edits back to OSM. I receive an error : (412) Precondition failed: Node ______ is still used by ways ______. Any ideas on what I might be doing wrong? 

thanks,
neil

**Comment by ThomasEmge** [comment]
It could be a bug. I'll check on why it is happening. In the meantime you might want to try to move the line endpoint and digitize a new line into the desired location.

**Comment by NeilLoehlein** [comment]
Thanks for looking into it. I'll stick with moving the line endpoint and creating a new line for now.

**Comment by NeilLoehlein** [comment]
Hi Thomas,
I uninstalled and reinstalled the ArcGIS OSM Editor, and I'm still running into the issue of deleted nodes when I split a way. Is there something beyond a reinstall that I need to do to solve this problem?

thanks,
Neil

**Comment by ThomasEmge** [comment]
Neil,

the error is fixed in the source code but the new tools haven't been released yet. Unfortunately you are stuck right now with moving the end point until we have a new official release.

**Comment by NeilLoehlein** [comment]
Ah, I see. Thanks for the clarification, and thanks again for taking care of the bug. I'm looking forward to working with the new version when it's available.
