### ISSUE TITLE
Error when trying to edit Lanes tag

### ISSUE THREAD

**Issue by NeilLoehlein** [Esri/arcgis-osm-editor#111]
I'm trying to edit the number of lanes with the ArcGIS OSM Editor and when I attempt to upload the edits back to OSM I keep receiving an error message (#412).
It reads, "Precondition failed: Way _________ requires the nodes with id in (0), which either do not exist, or are not visible." Any idea what may be causing this error? I tried editing just one segment, and even this threw an error.

thanks,
Neil

**Comment by ThomasEmge** [comment]
If the issue still remains, please reopen.
