### ISSUE TITLE
Unable to edit feature - Feature is a member of a relationship class

### ISSUE THREAD

**Issue by markvolzlyoncounty** [Esri/arcgis-osm-editor#112]
While trying to edit a street that was realigned I got an error:  The Feature (OSMID: 18140585) you are attempting to change is a member of relation (Relation ID: 3545755).  This action is currently not supported and the edit operation is aborted.

Questions:  
How do I view features that are in a relationship class
How do I remove the relationship so I can edit features that are part of a relationship class?

**Comment by mboeringa** [comment]
You should be very careful in not mixing two things up:

- ArcGIS and the ESRI geodatabase know the concept of _**Relationship Classes**_. These are ArcGIS specific (or more general RDBMS relational database) specific constructs and objects similar to how a geodatabase contains "Feature Classes", or other types of ESRI designed geodatabase features.

- OpenStreetMap has the concept of _**relations**_, which can be of varying types (multipolyon, route etc.). These are OSM specific constructs that are used to group things together via their OSM IDs. They are not dissimilar to RDBMS relations, but are certainly not the same as well, as implemented in the key-value tagging concept of OSM.

ArcGIS is capable of editing the **ESRI Relationship Class**, the ArcGIS Editor for OpenStreetMap _***is not***_ capable of editing **OSM relations**.

This may be a disappointment, but if you really have the desire to work with OSM relations, I really recommend you to use a tool like JOSM, that has clear and powerful tools to handle them.

Also mind that if you do intend to start editing relations via JOSM, that you will need a thorough understanding of the OSM relations concept (especially with OSM multipolygons). Be extremely careful, and don't remove or modify relations unless you are 100% certain what you are doing. Relations are a hot topic in OSM, and many users maintain complex (bus)route networks with them and will be upset if another user breaks them by an improper edit.

**Comment by markvolzlyoncounty** [comment]
Thank you for your reply and helping me clarify relations.  After a second download I did not have that issue, so I am guessing something just went wrong as opposed to me doing something wrong.
