### ISSUE TITLE
How can I install OSM editor on 10.2.0?

### ISSUE THREAD

**Issue by blvd20** [Esri/arcgis-osm-editor#127]
I saw the note,But don't understand why there isn't a installer for arcgis 10.2.0. I have 10.2.0 on my windows ,what should I do if I want to use this tool??thx

**Comment by ChanglongGu** [comment]
I have the same problem with you

**Comment by skmoore** [comment]
@Jiaoweiquan You can download an installer for 10.2 here: https://www.arcgis.com/home/item.html?id=16970017f81349548d0a9eead0ebba39

**Comment by lkgrgwu** [comment]
@skmoore I tried it by failed .it requires 10.2.1 or 10.2.2

**Comment by bestsamsg** [comment]
> @skmoore I tried it by failed .it requires 10.2.1 or 10.2.2

same problem
