### ISSUE TITLE
Upload fails with HTTP 401 Error

### ISSUE THREAD

**Issue by Stezii** [Esri/arcgis-osm-editor#128]
I always receive the error message "401 not authorized" when trying to upload my revision table. I tested my workflow on different computers with different ArcGIS versions and various OSM accounts. I checked the dev upload endpoint, too. 

1. Download the data, e. g. via download/extract/symbolize model or step by step
2. Adding Editor extension to every Feature Layer
3. Editing, saving and exiting editor session. The revision table logs changes: ![screenshot](https://cloud.githubusercontent.com/assets/8927680/15469929/9bda511a-20ed-11e6-980a-60489e2a9f68.JPG)
4. Upload

Am I missing something? Is the error related to OAuth?

**Comment by mboeringa** [comment]
> Am I missing something? Is the error related to OAuth?

Please note I have no technical knowledge of OAuth myself, but your remark maybe true, there seems to have been a more generic issue with OAuth and OSM applications caused by an upgrade to Python 3 on one of the OSM servers. See this post by one of the server admins on the GIS Nabble website:

http://gis.19327.n5.nabble.com/oauth-api-errors-td5874054.html

It seems to be fixed according to the remark.

**Comment by Stezii** [comment]
I'm still facing the issue.

**Comment by mboeringa** [comment]
@ThomasEmge ?

**Comment by ThomasEmge** [comment]
Not sure. The tools are just talking the OSM endpoint and the 401 is provided by the OSM server. I just tried to upload and it seems that in general the endpoint is working. Are you working behind a proxy server?

**Comment by Stezii** [comment]
No proxy. I tried uploading in multiple networks on various computers with ArcGIS 10.3 and various OSM user ids. So in my opinion, there's an issue with my workflow. 

I captured it here: http://sendvid.com/7838gqri (without adding symbology template this time)

**Comment by ThomasEmge** [comment]
That workflow looks ok to me. Have you tried using your email as opposed to the user name?

**Comment by Stezii** [comment]
Jup. I can insert any username and password. After 1 sec the 401 error appears.

**Comment by ThomasEmge** [comment]
Hmm, I am starting to run out of ideas. Would you feel comfortable to install fiddler on your machine and listen to the traffic? There are two requests going out to the OSM server; the first is a generic request and the second one retrieves user information and it needs to be authenticated. If the first one fails then we have a generic network issue, if the second one fails then it will be tricky to troubleshoot.

**Comment by Stezii** [comment]
GET http://www.openstreetmap.org/api/capabilities HTTP/1.1
Authorization: Basic c3RlZmFuLnppbW1lcl9zaGJAdC1vbmxpbmUuZGU6YXNkZmprbPY=
Host: www.openstreetmap.org
Connection: Keep-Alive


HTTP/1.1 200 OK
Date: Thu, 26 May 2016 22:16:45 GMT
Server: Apache/2.4.7 (Ubuntu)
Cache-Control: max-age=0, private, must-revalidate
Vary: Origin,Accept-Encoding
X-XSS-Protection: 1; mode=block
X-Request-Id: V0d1zX8AAQEAACwmTEAAAAB
X-Frame-Options: SAMEORIGIN
X-Runtime: 0.010300
X-Content-Type-Options: nosniff
X-Powered-By: Phusion Passenger 5.0.28
ETag: W/"b69f71c4d445c39807f17070e86935e4"
Status: 200 OK
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/xml; charset=utf-8
Content-Length: 727

<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="OpenStreetMap server" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
  <api>
    <version minimum="0.6" maximum="0.6"/>
    <area maximum="0.25"/>
    <tracepoints per_page="5000"/>
    <waynodes maximum="2000"/>
    <changesets maximum_elements="50000"/>
    <timeout seconds="300"/>
    <status database="online" api="online" gpx="online"/>
  </api>
  <policy>
    <imagery>
      <blacklist regex=".*\.googleapis\.com/.*"/>
      <blacklist regex=".*\.google\.com/.*"/>
      <blacklist regex=".*\.google\.ru/.*"/>
    </imagery>
  </policy>
</osm>


------------------------------------------------------------------

GET http://www.openstreetmap.org/api/0.6/user/details HTTP/1.1
Authorization: Basic c3RlZmFuLnppbW1lcl9zaGJAdC1vbmxpbmUuZGU6YXNkZmprbPY=
Host: www.openstreetmap.org


HTTP/1.1 401 Unauthorized
Date: Thu, 26 May 2016 22:16:46 GMT
Server: Apache/2.4.7 (Ubuntu)
Cache-Control: no-cache
Vary: Origin
X-XSS-Protection: 1; mode=block
WWW-Authenticate: Basic realm="Web Password"
X-Request-Id: V0d1zn8AAQEAACwmTMAAAAB
X-Runtime: 0.032953
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Powered-By: Phusion Passenger 5.0.28
Set-Cookie: _osm_session=31e88aa4cf2532ac8f8094b0fa576b71; path=/; HttpOnly
Status: 401 Unauthorized
Content-Type: text/html; charset=utf-8
Content-Length: 25

Couldn't authenticate you

------------------------------------------------------------------

PUT http://www.openstreetmap.org/api/0.6/changeset/create HTTP/1.1
Authorization: Basic c3RlZmFuLnppbW1lcl9zaGJAdC1vbmxpbmUuZGU6YXNkZmprbPY=
Host: www.openstreetmap.org
Content-Length: 317
Expect: 100-continue

<?xml version="1.0" encoding="us-ascii"?><osm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="0.6" generator="ArcGIS"><changeset id="0"><tag k="created_by" v="ArcGIS Editor for OpenStreetMap (10.2)" /><tag k="comment" v="added building" /></changeset></osm>
HTTP/1.1 401 Unauthorized
Date: Thu, 26 May 2016 22:16:46 GMT
Server: Apache/2.4.7 (Ubuntu)
Cache-Control: no-cache
Vary: Origin
X-XSS-Protection: 1; mode=block
WWW-Authenticate: Basic realm="Web Password"
X-Request-Id: V0d1zn8AAQEAACwmTgAAAAB
X-Runtime: 0.011187
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Powered-By: Phusion Passenger 5.0.28
Status: 401 Unauthorized
Content-Type: text/html; charset=utf-8
Content-Length: 25

Couldn't authenticate you

------------------------------------------------------------------

**Comment by Stezii** [comment]
I found the reason. My password contained the character 'ö'.
"Upload OSM Data" cannot handle this. It's a bug

**Comment by ThomasEmge** [comment]
Good find. It will be in the upcoming patch.
