### ISSUE TITLE
OSM File Loader (Load only) failes at Append step

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#130]
Hi @ThomasEmge ,

I have now finally found the time to install 10.4.1, allowing me to try out the new OSM File Loader (Load only).

Unfortunately, I am running into an issue when the tool gets to the point of the **Append** process. As you can see from the image, I am running the tool as 32 bit foreground process. The error message seems related to issue #126 and the remark you made at https://github.com/Esri/arcgis-osm-editor/issues/126#issuecomment-221124740, although in the case of issue #126, the process did not fail at the **Append** stage.

By the way, you are referring in https://github.com/Esri/arcgis-osm-editor/issues/126#issuecomment-221124740 to an API error, and the link there apparently points to a code line involving the ArcGIS RunTimeManager, so does this mean it requires a fix to that core component (and thus may take some time to get fixed, as needing an update of ArcGIS itself?).

![append_error](https://cloud.githubusercontent.com/assets/7635726/15794825/2a1e35aa-29ee-11e6-81b9-d7f1f62f7b13.jpg)

**Comment by ThomasEmge** [comment]
I think you are running into another issue that we found last week that has to do with running the loader on a single thread. We are finishing up testing the recent code changes and will post a patch soon.
Some details here: Since this tool is designed in a semi-parallel processing fashion it follows the default gp rules https://desktop.arcgis.com/en/arcmap/latest/tools/environments/parallel-processing-factor.htm. Which means if you are running it on a 2 core machine and don't specify anything else, the default of half the cores results in 1 process and there we had an issue.

**Comment by mboeringa** [comment]
Thomas, I have a 4 core machine (Core i5) and set the parallel processing factor to the value "3". According to the documentation, this should result in 3 cores max being used (there is also the confusing percentage option, but using a value with just the number of cores and no percentage character, should work also if I understood the parallel processing documentation well).

**Comment by ThomasEmge** [comment]
Did you set the PATH system environment variable to include your ArcGIS Python directory (another thing the patch will fix)?

**Comment by mboeringa** [comment]
When I looked at my Path, it was initially set to:

**Comment by mboeringa** [comment]
@ThomasEmge ,

Any update as to when the bugfix release might be available? Still a chance it can be released before the UC of this year? I guess you are all tied up in pre-conference preparations by now...

I would still love to try it out, especially now I fixed a blocking 10.4.x release related bug in my own OpenStreetMap renderer.

**Comment by mboeringa** [comment]
@ThomasEmge ,

I have now installed the latest release from the files you send. However, when I attempt to use **OSM File Loader (Load only)** tool, I still get an error, see the attached image. I am running this with 64-bit background processing installed, and it doesn't matter whether I enable or disable it, in both instances it failes.

May Windows system Path contains a reference to the following folder (which exists):
**C:\Python27\ArcGISx6410.4**

![load_error_update1](https://cloud.githubusercontent.com/assets/7635726/16054522/d212e58a-326d-11e6-9b90-702e2e063cd8.jpg)

**Comment by ThomasEmge** [comment]
This looks like a remainder from the previous issue. Please go to the folder specified in your workspace parameter (or your temp folder) and delete the latvia_latest_nX, latvia_latest_wX, latvia_latest_rX geodatabases.

**Comment by ThomasEmge** [comment]
The reference in the windows system path is no longer necessary and should be ignored.

**Comment by mboeringa** [comment]
@ThomasEmge ,

Besides cleaning up that, I noticed the **64 bit** Bin installation directory of the Editor, does not have an **OSMEditor.dll** file, is that correct?

I also see these *.pdb debugging? stuff files dating the third of December 2015 in my **32 bit** installation folder of the Editor. Do I need to clear out these as well and just leave the DLLs and the XML setting files? By the way, the XML files are also not present in the **64 bit** folder.

**Comment by ThomasEmge** [comment]
Please delete the existing OSM Editor folders and then use the installer files I send along. I don't think the XML setting files need to be in the 64bit folder, the tools should check a number of locations. The xml files in the same folder as the dlls are the last resort.

**Comment by mboeringa** [comment]
@ThomasEmge ,

I will try that and report back results once I have them. However, in the mean, could you possibly try to load Latvia from Geofabrik as well using the latest version?

I have now used it to load Latvia again using the "old" **Load OSM File** tool in the toolbox. However, I am seeing a number of incorrect road lines being generated near the city of Jelgava. See the attached images, the first with the wrong line work, the second from the OpenStreetMap website.

![loader_error_roads](https://cloud.githubusercontent.com/assets/7635726/16060461/1fddcb8a-3288-11e6-8af3-f8d3ee1b66f1.jpg)
![loader_error_roads_osm_website](https://cloud.githubusercontent.com/assets/7635726/16060467/24dac4a8-3288-11e6-9820-155062d5ca8c.jpg)

**Comment by ThomasEmge** [comment]
Most likely these are routes which are usually relations in OSM terms. It depends on the type of route how detailed it is. Hiking routes are a lot more detailed than 'logical' routes like train and bus routes that are just a combination of stops. You might need an additional filter to exclude these types of entities.

**Comment by mboeringa** [comment]
They indeed seem to have the **route=road** tag, additionally to **highway=primary**, the latter tag being responsible for them to show up in the rendered map. I am slightly baffled I haven't seen this much more. There are a gazillion routes in OSM. It maybe that most users a more diligent, and define the routes based on true highway geometries, or don't add the **highway=x** tag to routes.

Question: Is it safe to simply filter by:

**route IS NULL OR route IN ('','no')**

Or will I loose true highways as well? Does a defined route always duplicate the existing geometries (I guess so?), so I can safely filter them out?

**Comment by ThomasEmge** [comment]
No that is not the reason. The issue you are seeing is due to an out of order listing of the way comprising the route. It might have been there for some time.
Bottom line is that is a bug.

**Comment by mboeringa** [comment]
> Bottom line is that is a bug.

Do you mean the data as stored in the Geofabrik files is in error (and in that case also the data returned by the OSM XAPI, as I - as a double check - also downloaded data straight from the API using QGIS and that showed the same issues), or do you mean there is still some corner case bug in the OSM Editor's load tool?

**Comment by ThomasEmge** [comment]
No, it is a bug in the OSM Editor tools. Not sure when I discovered that relations don't need to be in sequential order. I remember doing steps to check and to ensure the order for relations for the new loader tool however the code for the existing loader should be fairly untouched since the last release.

**Comment by mboeringa** [comment]
Thomas,

I now see a similar issue in a map I rendered from Australia based on the old existing data loader, however in the latest incarnation you send. I do think it may have been introduced with the last changes to the tools, as I have rendered Australia before, and did not see it. See the comparison based on the old rendering of the 25th August 2015 (left part of the image) that does not show this issue, and the new rendering that does (right part of the image):

![loader_error_rivers](https://cloud.githubusercontent.com/assets/7635726/16091664/f9d91d4c-3334-11e6-85c4-0a8803ac69d6.jpg)

**Comment by mboeringa** [comment]
@ThomasEmge ,

I have now re-installed the 64bit version of the ArcGIS Editor for OpenStreetMap. Before doing that, I cleaned up the previous installation by first running the uninstall option for the Editor, and then removing the left over program folders in Windows 32bit and 64bit folder (**C:\Program Files (x86)\ESRI\OSMEditor** and **C:\Program Files\ESRI\OSMEditor**). I also cleaned up any split-up **osm** files that the new loader creates, and the multiple file geodatabases it uses for temporary storage as you pointed out.

I then re-booted the PC and opened ArcGIS. I set the multi-processing factor to 3, and scratch workspace to some other drive than the current workspace and Windows system drive.

Trying to run the process both as 64bit background (that I have installed with ArcGIS 10.4.1) and as 32bit foreground both resulted in the same error, see below. Notice that the loading of the nodes is reported as having been "done", yet the processing time for that step is registered at just 2 seconds, which is clearly falls, so it fails at the node loading step. I do see it properly parsing the osm file into smaller units, and creating the multiple temporary file geodatabases in the same folder as my scratch workspace file geodatabase.

![load_error_update1_reinstall_foreground](https://cloud.githubusercontent.com/assets/7635726/16094346/1b497d9a-3340-11e6-9f8b-c252f8617fe9.jpg)

**Comment by ThomasEmge** [comment]
Hmm, what is your Python directory?

**Comment by mboeringa** [comment]
> Hmm, what is your Python directory?

There are two, both installed by ArcGIS:

C:\Python27\ArcGIS10.4
C:\Python27\ArcGISx6410.4

The second 64bit folder is currently the last entry in my Windows Path, the other folder is not referenced.

I never installed Python myself, I just use what ArcGIS installed. I am still running Windows 7.

**Comment by ThomasEmge** [comment]
The tool is attempting to read the _PythonDir_ value from the _HKEY_LOCAL_MACHINE\SOFTWARE\ESRI\Python10.4_ hive in the registry. From there it will determine the path of the python executable. I was thinking that your might folder name might have additional spaces in the path that are not properly escaped. (Not that it should be an issue but I am fishing for ideas). Let me check if I can organize a Windows7 testing machine.

**Comment by mboeringa** [comment]
@ThomasEmge ,

D!mn, I now set the parallel processing factor to a value of **75%** instead of **3**, and it now seems to continue without error!

Do you somewhere in the code directly use this value? Or is this some bug in ArcGIS itself, because this behaviour and failure is not consistent with ArcGIS's Help, that states _that one should be able to directly specify the number of cores to use as well_, although most examples show percentage.

http://pro.arcgis.com/en/pro-app/tool-reference/environment-settings/parallel-processing-factor.htm

**Comment by ThomasEmge** [comment]
Both numbers should work. I just finished loading Latvia with a _Parallel Processing Factor_ of 3. What are your language settings?

**Comment by mboeringa** [comment]
> Both numbers should work. I just finished loading Latvia with a Parallel Processing Factor of 3. What are your language settings?

It now successfully finished in just 23 minutes!..

I run a Dutch version of Windows, so my language settings are "Netherlands / Dutch" with "," or comma as decimal separator. Keyboard layout is just US International for the Netherlands.

**Comment by mboeringa** [comment]
> Both numbers should work. I just finished loading Latvia with a Parallel Processing Factor of 3. What are your language settings?

@ThomasEmge:

One extra observation that may be of use debugging, is that I have noticed an important difference between the temporary processing results in case of setting a parallel processing actor of 3, and one of 75%.

In case I set a parallel processing factor of **3**, I see the tool generating **6** temporary **osm** files in my scratch workspace:

**latvia-latest_r0.osm
latvia-latest_r1.osm
latvia-latest_r2.osm
latvia-latest_w0.osm
latvia-latest_w1.osm
latvia-latest_w2.osm**

Looking at the file names, I guess these represent the relation and way features of the osm files, spread across 3 sets of files for a processing factor of 3. **THIS FAILS WITH THE COM ERROR!**

In case I set a parallel processing factor of **75%**, I see the tool generating **3** temporary osm files:

**latvia-latest_n0.osm
latvia-latest_r0.osm
latvia-latest_w0.osm**

Notice that, additionally to the relation and way files, there now is also a "_n0" nodes file, that is missing when I set the factor to 3. With this setup, the tool **SUCCEEDS**! 

Notice also that in both setups with factor 75% or 3, it generates two temporary file geodatabases for the nodes:

**latvia-latest_n1.gdb
latvia-latest_n2.gdb**

It actually suggest this may be related to what you wrote about in https://github.com/Esri/arcgis-osm-editor/issues/130#issuecomment-224085772 that related to single / multi-threaded processing. It suggests the only way the tool properly runs at my PC, is if it actually **_does not do parallel processing_**, because with the factor set to 75%, it just generates a single set of osm files to process, whereas with a factor of 3, it attempts to generate 3 sets of temporary osm files, but somehow fails to generate the node files.

**Comment by ThomasEmge** [comment]
The percent issue is indeed a bug and will be fixed.
The fact that you are not seeing nX files when the factor is set to 3 means that the load attempt has already failed and cleaned up after itself. I am still thinking of reasons why the code wouldn't be able to detect the python environment.

**Comment by mboeringa** [comment]
> The fact that you are not seeing nX files when the factor is set to 3 means that the load attempt has already failed and cleaned up after itself. 

Yes, I have just noticed this while monitoring the creation of the files during a new run with latest setup you send me. The "_n0..x" files are initially created, but indeed get cleaned up at the exact moment the COM error appears. I can see this happening live in the Windows explorer.

> I am still thinking of reasons **why the code wouldn't be able to detect the python environment**.

Are you referring to the fact that the parallel processing factor does not seem to be taken into account when the process does succeed with a setting of 75%, as I only apparently see one process being spawned?

**Comment by mboeringa** [comment]
@ThomasEmge,

I see you added two commits related to the percentage issue. Does this also fix the parallel processing issue itself? Do you still want me to test the last version you send via e-mail and download link? I didn't have time yesterday evening, so it was on my TO-DO for the coming hours... Or do these commits supersede that release?

By the way, this is from the previous release that fixed the "spaghetti". The region near Jelgava now looks fine!

![loader_error_roads_fixed](https://cloud.githubusercontent.com/assets/7635726/16160257/6e0d31e2-34c7-11e6-8604-f4c1736bbccb.jpg)

**Comment by ThomasEmge** [comment]
Yes, the latest commit includes the percentage fix and hopefully the fix for you with respect to parallel loading. Please use the download link from yesterday.

**Comment by mboeringa** [comment]
@ThomasEmge ,

I have send you via e-mail two mails with debug logs for running the tool with a Parallel Processing Factor of 3 ,and 75%. If you somehow did not receive them, please let me know.

**Comment by ThomasEmge** [comment]
@mboeringa The sample Bilboa dataset loads ok, so you are correct in your statement that it is not a dataset issue. However I am not seeing your reported load failure with the relations either. Foreground and background processing are finishing ok.

**Comment by mboeringa** [comment]
@ThomasEmge ,

I am going to provisionally close this. I don't know what exactly changed, but even before installing the last release you send me, I finally got results of the background processing.

Now, after some 8 to 10 imports using background processing, only one failed. Foreground processing seems to work as well.

Maybe it is still some "file-in-use" issue or so, but with the latest testing, I can't come up with anything reproducible, and as stated above, I now have seen the background processing properly working.

So, my "green light" for now for this issue!

**Comment by mboeringa** [comment]
@ThomasEmge,

I am re-opening this as I have a remaining question regarding this issue. While using the refactored **Download OSM Data (XAPI)** tool, I realized that especially with the specific functionality of this tool, it is very easy to create an OSM file that e.g. does not contain relations, as the tool allows to selectively download only a specific data type (node, way or relation).

Do you actually handle this properly in the code, because some of the temporary datasets (Feature Classes) created may have no records? Does it actually matter at all?

I encountered such a situation while using the tool, and setting it to only load ways.

This resulted in a failed attempt to merge / append the temporary relations geodatabases. If I look at the temporary databases after the failed execution (they have not been cleaned up because of the failure), I only see one of the geodatabases having a line and polygon feature class, the three others don't, this would be quite consistent with the error message of the **Append** I am seeing, stating that 

**"ERROR 000338: Inputs must be either all Feature Classes, Raster or Tables, not mixed"**

**Comment by mboeringa** [comment]
Hi @ThomasEmge ,

Here is a visual of the issue of the missing Feature Classes the likely cause the Append fail. Notice only one of the four geodatabases has feature classes, and even those are empty without records (this is not visible in the Catalog window screenshot of course, only the presence / absence of the FCs)

![load_error_append_no_feature_classes](https://cloud.githubusercontent.com/assets/7635726/16854626/1c9db772-4a12-11e6-8ae3-b7a071fd0825.jpg)
