### ISSUE TITLE
"OSM File Loader (Load only)" tool does not check for unique Feature Class names

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#133]
This is a relatively minor issue, but I noticed the "OSM File Loader (Load only)" tool does not check for unique Feature Class names. The tool requires the user to specify three feature class names for the Point, Line and Polygon feature classes, but it does not check if they are unique. If I deliberately insert the same path multiple times, the tool will start, but eventually fails with a "schema" error once it gets to ways processing. See the attached image.

It is a minor issue, but it would be good if the tool (or toolvalidation) scripting enforced unique names for the feature classes.

![loader_error_non_unique_filename](https://cloud.githubusercontent.com/assets/7635726/16295714/a9f9e5fa-3928-11e6-90de-01cf6a0beab5.jpg)

**Comment by ThomasEmge** [comment]
I'll include a fix for this.

**Comment by ThomasEmge** [comment]
@mboeringa I retested with the Bilbao osm file you had send me. Nodes, ways, and relations are loading ok.

**Comment by mboeringa** [comment]
> @mboeringa I retested with the Bilbao osm file you had send me. Nodes, ways, and relations are loading ok.

@ThomasEmge 
You mean to say you can confirm the issue of the background loading is not caused by the used Bilbao osm file, but some other remaining problem in the code?

By the way, for those reading this, these last two posts by Thomas and me are not related to this closed issue of non-unique feature class names... That was fixed in #133.

**Comment by ThomasEmge** [comment]
@mboeringa Ups, I picked the wrong issue thread.
