### ISSUE TITLE
Discrepancy between Point/Polyline/Polygon feature classes' shapefield index name created by the Load OSM File tool

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#135]
In the latest test build, there is a minor discrepancy between the index names created by the **Load OSM File** tool: the Point feature class' index name is "FDO_SHAPE", and the Polygon and Polyline feature classes have a spatial index named "SHAPE_INDEX". Maybe good to unify them? (what is the default in ArcGIS?, the OSM File Loader creates "FDO_SHAPE" as well, doesn't it?)

**Comment by ThomasEmge** [comment]
Application behavior generates spatial index called "FDO_SHAPE" and the geoprocessing framework calls the spatial index "SHAPE_INDEX".
