### ISSUE TITLE
Bug in "Download OSM Data (XAPI)" toolvalidator script

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#137]
Hi @ThomasEmge 

I have tried to run the new version of the **Download OSM Data (XAPI)** tool. However, even though there are fixes for other issues visible, it seems there is a new blocking issue introduced in the toolvalidator script.

I first attempted to download with my Data Frame set to the projected coordinate system **WGS 1984 Web Mercator (auxiliary sphere)**. Even though it would be desirable if the tool was simply able to convert from this projected system to WGS 1984 decimal degrees, like QGIS does, it at least blocked with a warning that it needed geographic coordinated ("Please specify extent coordinates in geographic coordinates").

I subsequently chose the **WGS 1984** selected from the **Geographic Coordinate Systems** list in ArcMap as the coordinate system for the data frame, but discovered this still failed with the error message in the following image:

![xapi_extent_problem](https://cloud.githubusercontent.com/assets/7635726/16496183/0e0b5ede-3ef1-11e6-842b-00426245d5f0.jpg)

I decided to debug this, and wrote a debugging version of the toolvalidator script. It inserts the line number and error message as the parameter error message. This resulted in the following message displayed:

![xapi_extent_problem_debugging](https://cloud.githubusercontent.com/assets/7635726/16496197/19d86c70-3ef1-11e6-8f81-2059fd7551c4.jpg)

Line number 49 points to the following line of code in the modified toolvalidator script:

`                    if locale.atof(coordinates[0]) < -180 or locale.atof(coordinates[0]) > locale.atof(coordinates[2]):`

It seems the "," may be the culprit, but isn't **locale.atof** supposed to take care of exactly this type of problem? I am not to familiar with the locale module yet, but it clearly throws an exception for this line (although, as you can see if you evaluate the code, it is not captured as "locale.Error", but a generic exception.)

[XAPI_toolvalidation_debug_script.zip](https://github.com/Esri/arcgis-osm-editor/files/341880/XAPI_toolvalidation_debug_script.zip)

**Comment by ThomasEmge** [comment]
I have now tested with three different configurations:
1. English OS, German number/date formatting
2. English OS, German language display
3. English OS, Schema region to German for non-Unicode programs

For each of these tests the download my download succeeded. Bottom line is so far I have been unable to reproduce the issue.

**Comment by mboeringa** [comment]
@ThomasEmge 

Just for info: If I type these two lines of code in a script window in PyScripter:

```
import locale

locale.atof("13,3890120178244")
```

and then hit the "Debug" button in PyScripter, I go straight into the **locale** module and get exactly the same error message as I see in ArcGIS. See the attached image. 

I don't know how to interpret this at the moment...

![pyscripter_locale](https://cloud.githubusercontent.com/assets/7635726/16499841/579a8bf4-3f02-11e6-9d94-983193869cff.jpg)

**Comment by mboeringa** [comment]
@ThomasEmge 

I don't understand the Python **locale** module... ;-(

If I look at the code, I see the **atof()** function referencing a **localconv()** function. However the localcon() function is just a simple dictionary, that containts the C locale defaults, where the "decimal_point" key is simply hard-coded associated with the value "." point.

```
    def localeconv():
        """ localeconv() -> dict.
            Returns numeric and monetary locale-specific parameters.
        """
        # 'C' locale default values
        return {'grouping': [127],
                'currency_symbol': '',
                'n_sign_posn': 127,
                'p_cs_precedes': 127,
                'n_cs_precedes': 127,
                'mon_grouping': [],
                'n_sep_by_space': 127,
                'decimal_point': '.',
                'negative_sign': '',
                'positive_sign': '',
                'p_sep_by_space': 127,
                'int_curr_symbol': '',
                'p_sign_posn': 127,
                'thousands_sep': '',
                'mon_thousands_sep': '',
                'frac_digits': 127,
                'mon_decimal_point': '',
                'int_frac_digits': 127}


def atof(string, func=float):
    "Parses a string as a float according to the locale settings."
    #First, get rid of the grouping
    ts = localeconv()['thousands_sep']
    if ts:
        string = string.replace(ts, '')
    #next, replace the decimal point with a dot
    dd = localeconv()['decimal_point']
    if dd:
        string = string.replace(dd, '.')
    #finally, parse the string
    return func(string)
```


So the code line

```        
    dd = localeconv()['decimal_point']
    if dd:
string = string.replace(dd, '.')```

is doing what??? Replace a dot with a dot???

Is this somehow an ArcGIS Python installation issue, and should the install of the **locale** module normall

**Comment by mboeringa** [comment]
Hmmm, well, I see I am jumping to conclusions waaaay to quickly, the excerpt I posted showing the **localconv()** is only a secondary option upon import failure of the _locale module. Should he scrolled up propely in PyScripter...

```
try:

    from _locale import *

except ImportError:

    # Locale emulation

    CHAR_MAX = 127
    LC_ALL = 6
    LC_COLLATE = 3
    LC_CTYPE = 0
    LC_MESSAGES = 5
    LC_MONETARY = 4
    LC_NUMERIC = 1
    LC_TIME = 2
    Error = ValueError

    def localeconv():
        """ localeconv() -> dict.
            Returns numeric and monetary locale-specific parameters.
        """
        # 'C' locale default values
        return {'grouping': [127],
                'currency_symbol': '',
                'n_sign_posn': 127,
                'p_cs_precedes': 127,
                'n_cs_precedes': 127,
                'mon_grouping': [],
                'n_sep_by_space': 127,
                'decimal_point': '.',
                'negative_sign': '',
                'positive_sign': '',
                'p_sep_by_space': 127,
                'int_curr_symbol': '',
                'p_sign_posn': 127,
                'thousands_sep': '',
                'mon_thousands_sep': '',
                'frac_digits': 127,
                'mon_decimal_point': '',
                'int_frac_digits': 127}
```

**Comment by mboeringa** [comment]
Well, so far for the crash course Python I am still a bit experiencing...

I wasn't yet familiar with the special "_Identifier" single underscore syntax, which essentially "hides", or better said makes private, some identifier like a function. In this case: 

`form _locale import *`

appears to simply do an import of the module itself within the **locale** module. A bit unusual, but not entirely illogical. So it simply refers to the "locale" module, and there is no additional "_locale" module in the Python install.

**Comment by mboeringa** [comment]
@ThomasEmge ,

Any news from the Python team you contacted regarding this issue?

**Comment by scw** [comment]
Hello @ThomasEmge and @mboeringa,

At [line 5 of download_using_xapy.py](https://github.com/Esri/arcgis-osm-editor/blob/38565575057cf350b942818268d8701e006f5f2c/src/data/download_using_xapi.py#L5, try adding this code:

```python
# register the default locale
locale.setlocale(locale.LC_ALL, '') 
```

That should initialize the locale engine to allow it to perform the translations correctly. If it doesn't, could you report what the output of these commands are on your machine?

```python
import locale
locale.setlocale(locale.LC_ALL, "")

print(locale.getlocale())
print('radix: "{}"'.format(locale.localeconv()["decimal_point"]))
```

**Comment by mboeringa** [comment]
@scw ,

Thanks, this fixes the issue. I have successfully downloaded an almost 200 MB osm file using the tool. The code change must be implemented both in the main script, but also in the toolvalidator script, as otherwise the toolvalidation will still block execution of the script.

@ThomasEmge : can you implement this in both scripts?

With this fix in, I think the toolbox is ready for release! (unless you intend to have a look into other outstanding - potential - issues related to the Network Datasets like https://github.com/Esri/arcgis-osm-editor/issues/131)

**Comment by mboeringa** [comment]
I think I can close this one for now, with the PR merged...
