### ISSUE TITLE
Potential issue with ways and relations processing in new OSM File Loader (Load only) tool

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#138]
Hi @ThomasEmge ,

I hope I am not bothering you to much with yet another potential issue, but I think there may be an important issue with the ways and relations processing in the new **OSM File Loader (Load only)** tool.

As I am currently unable to use my ArcGIS Renderer for OpenStreetMap with the new **OSM File Loader (Load only)** output due to a field naming conflict between the old **Load OSM File** tool and the new tool, I haven't yet properly evaluated the output of the new tool.

However, as a first test, I decided to download a section of Berlin with the Bode Museum (http://www.openstreetmap.org/relation/4211594), that we have been using to tackle the OpenStreetMap Simple 3D building relations in the solved issue #72.

Once I loaded the data with the new OSM File Loader, and selected buildings only using:

`
osm_building IS NOT NULL AND osm_building NOT IN ('no','')`

I noticed an issue though, there seemed to be an overlapping polygon feature at the same location as the Bode Museum's multipolygon relation. Subsequently, I discovered that this feature, which uses the Bode Museum's way outline, falsely carries the attributes of another way object. It shows up as a building feature with the tag:

**building=commercial**

However, there is no commercial building at this location, just the Bode Museum. Checking the individual ways, including the outline way of the Bode Museum on the OpenStreetMap website (http://www.openstreetmap.org/way/313659705), that does not carry any tags of its own, it became clear these tags must be coming from somewhere else, another feature. This is also confirmed by the wrong OSMID on the feature, which lists as **w14582095**. Checking this feature out on the OpenStreetMap website, it turned out to be another building quite some distance away from the Bode Museum. See this image, the lower left downward pointing arrow denoting the true  **w14582095** commercial building, the upper right one pointing to the Bode Museum:

![way14582095_true_location_osm_website](https://cloud.githubusercontent.com/assets/7635726/16527451/3f39777c-3fb7-11e6-96db-760ffe802752.jpg)

It appears there may be some issues with the indexes or dictionaries keeping track of the objects, maybe a similar issue as the one in #117?

Anyway, the following images show more detail and explain the issue in more detail. I have also included a ZIP from the Berlin OSM file I used, so you can test and see if you come up the same result.

As a start, the following image shows the Bode Museum multipolygon relation as it is visible on the OpenStreetMap website. Notice the relation ID of **4211594**:

![relation4211594_bode_museum_osm_website](https://cloud.githubusercontent.com/assets/7635726/16528910/fc92f48a-3fbf-11e6-8cb6-39f87ee724a3.jpg)

The second image shows the multipolygon relation as loaded by the "old" **Load OSM File** tool. Notice in the identify window that it has the proper OSMID as on the OpenStreetMap website. This looks good:

![way4211594_bode_museum_load_osm_file](https://cloud.githubusercontent.com/assets/7635726/16527449/3f3832e0-3fb7-11e6-9be2-d2f2574336bd.jpg)

Next up is the same multipolygon relation as loaded by the "new" **OSM File Loader (Load only)** tool. Notice this is also OK, and displaying the proper OSMID and properties / tags:

![relation4211594_bode_museum_osm_file_loader](https://cloud.githubusercontent.com/assets/7635726/16527447/3f2b377a-3fb7-11e6-9916-4f391a6235d4.jpg)

Now the issue though: by using the following selection statement:

`osm_building IS NOT NULL AND osm_building NOT IN ('no','') AND OSMID = 'w14582095'`

a building polygon representing the outline of the Bode Museum is selected. This has wrong polygon / way information associated with it. Remember that I checked the way outline of the Bode Museum on the OpenStreetMap website, and it did not have this information associated with it. Notice the OSMID displayed is **14582095**. By using this OSMID on the OSM website, I was able to identify the feature where these wrong tags came from, see the first image I posted of the secondary building some distance away from the Bode Museum.

You can also directly select it using this link:

http://www.openstreetmap.org/way/14582095#map=19/52.51053/13.37911

![way14582095_identified_osm_file_loader](https://cloud.githubusercontent.com/assets/7635726/16527448/3f2c1af0-3fb7-11e6-8bd8-5336e59c1e69.jpg)

*** EDIT: *** forgot the ZIP with the osm XML file, here it is:

[OSM_Berlin.zip](https://github.com/Esri/arcgis-osm-editor/files/343903/OSM_Berlin.zip)

**Comment by ThomasEmge** [comment]
Very nice catch. Thank you for the excellent detective work. The fix will go in very soon. 
The reason here was an 'incomplete' way ([id: 14582095](http://www.openstreetmap.org/way/14582095)) meaning that not all referenced nodes by the way where included in the osm file itself. The feature should have been ignored by the loading process.
Just out of curiosity how was this osm produced?

**Comment by mboeringa** [comment]
> Just out of curiosity how was this osm produced?

This is output of QGIS's **Download Data** option for OpenStreetMap (under the Vector \ OpenStreetMap menu option), which is essentially equivalent to the **Download OSM Data (XAPI)** option of the ArcGIS Editor (that I still can not run due to the blocking toolvalidator issue).

However, I wouldn't be surprised at all if there are a couple of other tools in the OpenStreetMap software ecosystem, that produce similar "incomplete" osm XML files. E.g. many editors also have options for downloading "incomplete members".

So it is definitely good to have this fix in, as there will undoubtedly be people with similar datasets trying to import with the ArcGIS Editor's options.

**Comment by mboeringa** [comment]
@ThomasEmge ,

Was this fix supposed to be included in the last files you made available? Because I still see the false commercial building after doing a re-import of the data...

Or is the fix only going in with the final build?

**Comment by ThomasEmge** [comment]
This fix should be in the latest build.

**Comment by mboeringa** [comment]
I re-installed fully??

Will look at this tomorrow. Its bed time here...

**Comment by mboeringa** [comment]
Wrong button...

**Comment by mboeringa** [comment]
> This fix should be in the latest build.

@ThomasEmge 

I now double checked, but it is still not good.

I first uninstalled the ArcGIS Editor for OpenStreetMap. Since I noticed the uninstall failed to delete the DLLs from the 64bit install folder (C:\Program Files\ESRI\OSMEditor), I deleted the "ESRI" folder manually. I guess the uninstall failed due to the fact that, in order to test previous DLLs you made available, I manually overwrote these files.

Anyway, after this clean up, I downloaded the files again from the link you made available, and re-installed. After a full reboot, I used the **OSM File Loader (Load only)** tool again to import my Berlin OSM XML file.

Same result, the false commercial building is still being created.

Are you absolutely sure the fix was included in the last build, and that you made the right setups available to me via the download link?

**Comment by ThomasEmge** [comment]
Yes, I double-checked yesterday as well.

Looking for the office building shows that it doesn't exist.
![berlin_office_building](https://cloud.githubusercontent.com/assets/1569501/16696969/39baac4a-44fc-11e6-895c-46f0ed2a0f01.PNG)

And here is the outline of the Bode Museum
![berlin_outline_bode_museum](https://cloud.githubusercontent.com/assets/1569501/16697010/711c58a0-44fc-11e6-8e09-b71b20f5a17b.PNG)

**Comment by mboeringa** [comment]
@ThomasEmge ,

I am getting this with the following query:

`osm_building IS NOT NULL AND osm_building NOT IN ('no','') AND OSMID = 'w14582095'`

Are you absolutely sure you supplied me with the right version of the tool??

![way14582095_false_location_osm_file_loader_release7](https://cloud.githubusercontent.com/assets/7635726/16697334/80746674-4549-11e6-9687-4d524980892a.jpg)

**Comment by ThomasEmge** [comment]
I just updated the download location. The commit and the setup build had indeed a different date.

**Comment by mboeringa** [comment]
> I just updated the download location. The commit and the setup build had indeed a different date.

Thanks, that looks much better! Just the Bode Museum multipolygon relation left as building:

![relation4211594_bode_museum_osm_file_loader_release8](https://cloud.githubusercontent.com/assets/7635726/16698719/f4db81ea-454f-11e6-9e74-104d87796575.jpg)

And with that, I think I can close this for now. I will keep an eye on other issues though in further testing.
