### ISSUE TITLE
Toolbox "alias" changed in latest 10.4x version of toolbox

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#140]
Hi @ThomasEmge  ,

I hadn't realized this before, but noticed the toolbox alias changed from "osmESRItools" to "osmtools" in the latest version. Is this a conscious decision, potentially for some technical reason?

Because this breaks some of my scripting... it is a breaking change. I can adjust for that, but would like to know if this isn't an accidental typo that will be reverted.

**Comment by ThomasEmge** [comment]
The alias was always intended to be "osmtools". Please take a look at some of the early server scripts we have https://github.com/Esri/arcgis-osm-editor/blob/master/src/data/svr_datadownload.py#L22

**Comment by mboeringa** [comment]
OK, I'll adjust.
