### ISSUE TITLE
Not able to use download openstreet map data tool. getting invailed geofiledatabase error, when pointing to geofiledata base.

### ISSUE THREAD

**Issue by LGuilliams** [Esri/arcgis-osm-editor#144]
using ArcGIS 10.4.1 for desktop (think it is the 32 bit version) version: 10.2.1.5686
using 32 bit version of OSM tools

Tool: Download OSM Data
OpenStreetMap base download URL: http://www.openstreetmap.org
Extent of data download: Same as Display
Top:2037667.829304
Left: -7015946.602653
Right: -7003274.648256
Bottom: 2026328.171188
Include all relation references (optional): Checked
Target feature dataset:C:\Users\user\Documents\ArcGIS\Project\Geodatabase.gdb\OSM
OpenStreetMap feature classes: not accessable

Error: Please Chose a valid geodatabase to host the target feature dataset.
ERROR -1
Please choose a valid geodatabase to host the target feature dataset.

When using the file icon: 
Will not allow the selection of the File Geodatabase. Only per exsiting Data elements inside of geodatabase file.

But get the same error. After requesting to overwrite data element.

When dragging the tool over to the Python console - No help on who to use it in Python land.

I have tried to use the openstreet map  download page, downloads a map file.
but get the same issue with the load osm file tool.

I'm at a lost and it seems that the tool help is not helpfull.

Thanks in advance....

BTW: Could not find a solution on the web. Do not have access to an enterprise (SDE) geodatabase. Just what comes with esri ArcGIS 

again 

Thanks in advance....

**Comment by ThomasEmge** [comment]
Could you please post the messages from the Download OSM tool itself. In the Geoprocessing results window, right-click on the message node and select 'Copy' from the context menu and past it here.
The result should kind of look like this:

Messages
Executing: OSMGPDownload http://www.openstreetmap.org "-63.0174291199082 17.9040838041371 -62.9193862322665 18.0127531436854" INCLUDE_REFERENCES E:\temp\osm.gdb\lux3 E:\temp\osm.gdb\lux3\lux3_osm_pt E:\temp\osm.gdb\lux3\lux3_osm_ln E:\temp\osm.gdb\lux3\lux3_osm_ply
Start Time: Fri Aug 05 14:51:57 2016
Debugging...
Starting OSM Data download request...
Resolving and downloading relation with id 1362232.
Resolving and downloading way with id 30814651.
Resolving and downloading way with id 30814650.
Resolving and downloading way with id 135251539.
Resolving and downloading way with id 25776674.
Resolving and downloading way with id 30814474.
Resolving and downloading way with id 30857588.
Resolving and downloading way with id 31102424.
Resolving and downloading relation with id 90162.
Resolving and downloading relation with id 2824823.
Resolving and downloading relation with id 1993832.
Resolving and downloading relation with id 1846740.
Resolving and downloading relation with id 1993779.
Resolving and downloading relation with id 1993677.
Resolving and downloading relation with id 1993713.
Resolving and downloading relation with id 2531266.
Resolving and downloading relation with id 1104125.
Resolving and downloading relation with id 4107888.
Resolving and downloading relation with id 1102480.
Resolving and downloading relation with id 82675.

**Comment by LGuilliams** [comment]
Hi Thomas,

The area size does to seem to matter. My current work around is to use
another process toe retrieve the data from OSM.
Msg from Ideal area:
Messages
Executing: OSMGPDownload http://www.openstreetmap.org "-61.7413461026826
10.5214323848164 -61.280325532803 10.7941781026096"
DO_NOT_INCLUDE_REFERENCES C:\Users\my\Desktop\newdata\POI2016\OSM.gdp
C:\Users\my\Desktop\newdata\POI2016\OSM.gdp\OSM_osm_pt
C:\Users\my\Desktop\newdata\POI2016\OSM.gdp\OSM_osm_ln
C:\Users\my\Desktop\newdata\POI2016\OSM.gdp\OSM_osm_ply
Start Time: Fri Aug 05 17:14:02 2016
Debugging...
Starting OSM Data download request...
The remote server returned an error: (400) Bad Request.
You requested too many nodes (limit is 50000). Either request a smaller
area, or use planet.osm
The OpenStreetMap response does not contain valid elements.
(OSMGPDownload) aborted by User.
Failed at Fri Aug 05 17:14:12 2016 (Elapsed Time: 9.72 seconds)

Msg for tiny area:
Messages
Executing: OSMGPDownload http://www.openstreetmap.org "-61.5263972470726
10.6486324 -61.4920097529274 10.6581056" DO_NOT_INCLUDE_REFERENCES
 C:\Users\my\Desktop\newdata\POI2016\OSM.gdp
C:\Users\my\Desktop\newdata\POI2016\OSM.gdp\OSM_osm_pt
C:\Users\my\Desktop\newdata\POI2016\OSM.gdp\OSM_osm_ln
C:\Users\my\Desktop\newdata\POI2016\OSM.gdp\OSM_osm_ply
Start Time: Fri Aug 05 17:17:58 2016
Debugging...
Starting OSM Data download request...
Unable to open the workspace at C:\Users\my\Desktop\newdata\POI2016.
Failed to execute (OSMGPDownload).
Failed at Fri Aug 05 17:18:22 2016 (Elapsed Time: 23.77 seconds)


BTW: I watched some Youtube videos, to make sure I was using the tool
correctly.
(Why is the OSM data diffuclt to access?)

Thank you,

regards,

**Comment by mboeringa** [comment]
> (Why is the OSM data diffuclt to access?)

_Because it is not stored in any of the commonly used data formats_ (shapefiles, Oracle Spatial, PostGIS or Microsoft SQL Server Geometry etc.), but in a dedicated format originally designed by those people who initiated the OpenStreetMap project, maybe or likely even Steve Coast (the founder of OSM) himself. This community project was not born in a big company, but more likely in the Steve's home office...

Even more important to understand about the way the data is stored in OpenStreetMap's PostgreSQL database (which is purely relational, and doesn't use nor need the PostGIS spatial extension of PostgreSQL), is that OpenStreetMap data is stored as nodes (vertices) and ways (lines) only. 

Yes, you read that right - _this may be utterly flabbergasting to you_ -**but there are no polygon geometries in the OSM main database**!

The data is stored in a way which slightly resembles the good old "ArcInfo" coverage format, which didn't store self contained Polygons as well, but just the lines defining border between two "polygons". However, contrary to that format which used "labelpoints" inside the network of polygons, OSM uses relations defined in a key/value dictionary like data storage to define what lines belong to what "multipolgyons / multipolygon relations" (this is how polygons are called in the OSM world).

You have to realize, Steve originally probably never envisaged storing "polygons", he originally set out to create a free alternative of a routable road network, AFAIK. Multipolygon relations only came later.

This all means that to create polygons from the "nodes" and "ways" data, ArcGIS needs to do a lot of processing of relations stored in the key/value dictionary structure in which a lot of the data of OSM is stored, including as distributed in OSM files. 

This is NOT an easy task, OSM has much freedom in its editor applications, and geometries can be complex and are quite regularly incompletely or ill defined by users. Actually, there are only a few applications that do a real good job at creating (multi)polygons from osm data. osm2pgsql is one, this ArcGIS editor is another, and there are not many others that can compete.

**Comment by ThomasEmge** [comment]
When you are going through the user interface of the geoprocessing tool, I highly recommend using the "Browse" (folder icon) button for the Target feature dataset parameter. What the tool is looking for at that point is a feature dataset inside a valid geodatabase. 
Based on your posting you are encountering two different errors:
- The first error message is telling you that you are requesting too much data through the OpenStreetmap server. The tool is making the request for data and the server is telling you "No, you can't have that much data. Please look for another way to get it." Usually that means you need to decrease your request area (zoom in on the map view) or directly go to a download site like http://download.geofabrik.de if you are looking for country wide data extracts.
- The second error is telling you that you are not using a valid geodatabase. Here is how the feature dataset is structured (for example: E:\temp\osm.gdb\lux3)

_E:\temp\osm.gdb_ --> This is the name of the file geodatabase. The name of a file geodatabase needs to have a gdb extension.
_lux3_ -->   This is the name of the feature dataset. If the feature dataset doesn't exists yet, the tool will create it. The geodatabase does however need to exist before the tool can be run and before you can specify the feature dataset.

For more information about feature datasets please take a look at the online help topic at http://desktop.arcgis.com/en/arcmap/latest/manage-data/feature-datasets/an-overview-of-working-with-feature-datasets.htm

**Comment by LGuilliams** [comment]
Mboeringsa: I have read about the data formats, before trying to use OSM
data... The (Why is the OSM data diffuclt to access?) was out of
frustration.

Thomas: I did try the method, you have suggested and get the following:

Messages
Executing: DownloadExtractSymbolizeOSMData2 "-61.514068 10.649063
-61.504339 10.657675" true
C:\Users\my\Desktop\newdata\POI2016Carribean\OSM.gdb\POIsample "OSM Group
Layer"
Start Time: Mon Aug 08 15:18:50 2016
Executing (Download OSM Data): OSMGPDownload http://www.openstreetmap.org
"-61.514068 10.649063 -61.504339 10.657675" DO_NOT_INCLUDE_REFERENCES
C:\Users\my\Desktop\newdata\POI2016Carribean\OSM.gdb\POIsample
C:\Users\my\Desktop\newdata\POI2016Carribean\OSM.gdb\POIsample\POIsample_osm_pt
C:\Users\my\Desktop\newdata\POI2016Carribean\OSM.gdb\POIsample\POIsample_osm_ln
C:\Users\my\Desktop\newdata\POI2016Carribean\OSM.gdb\POIsample\POIsample_osm_ply
Start Time: Mon Aug 08 15:19:32 2016
Debugging...
Starting OSM Data download request...
Unable to locate the osm_domains.xml (domain configurations) file.
Failed to execute (Download OSM Data).
Failed at Mon Aug 08 15:20:48 2016 (Elapsed Time: 1 minutes 16 seconds)
Failed to execute (DownloadExtractSymbolizeOSMData2).
Failed at Mon Aug 08 15:20:48 2016 (Elapsed Time: 1 minutes 58 seconds)

How do I determine the location of the osm_domains.xml and/or download it
and place it into the correct location?

**Comment by ThomasEmge** [comment]
You are almost there....

In ArcMap bring up the Editor toolbar (using the menu system you get there via Customize > Toolbars > Editor). On the toolbar goto Editor > Options ...  and select the OpenStreetmap tab on the dialog. 
This property sheet helps you specify the missing information. If the text box for OSM Domains is empty use the folder icon button on the right to select the file. The configuration files should be located in your install folder and this folder might by _C:\Program Files (x86)\ESRI\OSMEditor\Bin_ if you accepted all the default during installation. 
Once the xml files are specified for the domains and features, please save your current session, close ArcMap and then re-open ArcMap such that the updated information can be applied.

**Comment by mboeringa** [comment]
@ThomasEmge,

Regarding this particular issue: I never actually worked with this tool seriously, as my main tools have been the Load OSM File tool and the OSM Attribute Selector for rendering the data in my own processes.

However, purely as a test, I have now attempted to use this tool. I selected a small section of a city in the Netherlands, and choose deliberately to "Include all relation references". I know the Help states this is not common, but it should work. The tool started up and finished downloading relatively quickly. However, when it started to process the data, which in the Netherlands undoubtedly includes lengthy routes, the process seemed to go on for ever. It seems to use some very inefficient loading process, continuously re-indexing the target dataset, that is extremely slow. I left it running for a couple of days, just to see what would happen and exactly what data it had downloaded, and it wasn't finished! That is even longer than loading the entire Netherlands with the "old" Load OSM File tool... and one thing is sure: even with the relation references, it can only have downloaded a fraction of the data contained in the Netherlands extracts.

Can't the actual process of loading the data in the geodatabase be replaced by the "old" Load OSM File tool, as that tool also loads all the relation and tag data? Although the Load OSM File tool can't compete with the new multi-processing OSM File Loader, it is still light years more efficient than the code in this tool seems to be. 

The tool in its current state seems barely usable if and when the "Include all relation references" option is selected...

**Comment by ThomasEmge** [comment]
Well, the 3 loading tools have somewhat of a different audience. 

The Download OSM tool is intended to work in a ad-hoc mode where the user works with the current map extent to get OSM data. For urban areas you might run into situations where the request is hitting the download size limit. At that point you might want to use a download site like http://download.geofabrik.de to get the larger dataset as OSM files and then load the data into a file geodatabase with the Load OSM File tool. Both tools are designed to let the user edit the data and then upload the changes back to the OSM server.
The third loading tool drops the editing/uploading requirement and as such can make a handful of simplified assumptions about the data. As a consequence it is able to load the data faster than the other (editing) loader. You can still make local edits to the data but you are no longer able to send the changes back to the OSM server.
Now the "Include all relation references" parameter came in as suggestion from the OSM folks and early talks at Camp Roberts. The "quick download" you saw is only the beginning. After the initial extent download the tool takes a look at the incomplete mentioned relations and downloads these as well. All of it that is, relation, ways, and nodes. Then the tool examines the newly downloaded relation as well. If it mentions another relation then it will also download that relation and so forth. The process of downloading the relations by itself usually takes a couple of hours. 
I once tried the option for a street network around Munich and ended up with a European network of roads. We probably can say that it is a purely academic option for data loading and should only be used very sporadically.

**Comment by mboeringa** [comment]
> I once tried the option for a street network around Munich and ended up with a European network of roads. We probably can say that it is a purely academic option for data loading and should only be used very sporadically.

Well, that certainly explains the days wait... the Netherlands is full of routes too, so I guess it attempted to download half of Europe too. 

Yes, I understand and appreciate the slightly different audiences for the tools, and the editor support build in, but maybe it is good to remove the option, or limit the downloading to only the child members of the initially detected relations, instead of going on recursively? Because that is what I think JOSM also does: only load the members for the relations detected in the currently downloaded extent that is being edited, but not recursively. I wonder if that is even what the OSM folks truly suggested or meant by their request?
