### ISSUE TITLE
Unclosed and missing geometries in load results of latest build

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#145]
Hi @ThomasEmge ,

I have tried to use the latest build to download and process a section of Berlin again. I used the **Download OSM Data (XAPI)** option to download the data, which worked fine after setting the coordinate system of the data frame to geodetic WGS1984.

I then used the latest build to import the osm file using the **OSM File Loader (Load only)** tool.

I experienced two crashes, but also two successful finishes.

However, it appears there is now some issue with the processing of the geometries. The Bode Museum building is now completely missing, but I am also seeing another weird issue. Look at the appearance of the "outline" building in the lower right corner of this image:

![unclosed_geometry](https://cloud.githubusercontent.com/assets/7635726/17452501/eb2e0d3a-5b6f-11e6-8fbb-baf1b3b5dd2a.jpg)

No, it is not a separate line layer, it is the same polygon layer as the rest of the data, just no fill displayed by ArcMap, a typical sign that something is wrong in the actual geometry. When I zoom in far enough to cover the lower right corner of the building, it's fill starts to appear:

![unclosed_geometry_filled](https://cloud.githubusercontent.com/assets/7635726/17452504/f3f09eba-5b6f-11e6-8d7e-a38ea4e0759e.jpg)

Again a sign something is wrong with the geometry as written in the geodatabase.

Lastly, an image showing the context and the missing Bode Museum. Attached also the osm file I used for the import and downloaded with the XAPI option, see entirely below in this post.

![bode_museum_missing](https://cloud.githubusercontent.com/assets/7635726/17452508/fb168e84-5b6f-11e6-8402-5faf864dcf98.jpg)

[OSM_Berlin.zip](https://github.com/Esri/arcgis-osm-editor/files/404736/OSM_Berlin.zip)

**Comment by mboeringa** [comment]
@ThomasEmge ,

I just double checked, but a quick look seems to confirm that the "old" **Load OSM File** tool doesn't suffer from the same issue, and produces proper polygons. The Bode Museum isn't missing, and neither do I see a similar "unclosed" polygon issue. The data looks good.

**Comment by ThomasEmge** [comment]
Have you tried running the repair geometry tool on the data?

**Comment by mboeringa** [comment]
> Have you tried running the repair geometry tool on the data?

@ThomasEmge , yes, that fixes the geometry issues, I realize, looking at the geoprocessing history, that you don't yet incorporate a Repair Geometry step at the end of relation processing with the OSM File Loader (Load only) tool? It undoubtedly should if it is missing, considering the number or things it also fixes in the Load OSM File tools process flow.

The repair identified and fixed at least a dozen features with "incorrect ring order"...

**Comment by ThomasEmge** [comment]
Correct, that would be the step that needs to be added after handling the area relations - probably after the relations and then after the super-relations.

**Comment by mboeringa** [comment]
@ThomasEmge , I really would like to try a new build. I again, this time on a huge import of Italy as downloaded from Geofabrik, experienced a fatal crash of ArcMap. Totally gone. This seems to happen at the relations processing stage.

Is there a Repair Geometry step of the Polygon feature class before starting relations processing, I think I saw it listed?

Anyway, if you make a new build available, I'll give it a try.

**Comment by ThomasEmge** [comment]
I am not happy with the 'remains' of the Bode museum after the geometry repair. I'll need a little bit more time to check it out.

**Comment by mboeringa** [comment]
> I am not happy with the 'remains' of the Bode museum after the geometry repair. I'll need a little bit more time to check it out.

@ThomasEmge , I am getting this result when applying a Repair Geometry step after the import with the **OSM File Loader (Load only)** tool finished. This looks good. **Are you getting a different result?** Of course, applying the Repair Geometry only at the very end, may not be the same process flow as you currently implemented.

![bode_museum_repaired](https://cloud.githubusercontent.com/assets/7635726/17548246/423bd0ca-5eeb-11e6-8c23-4965e72faea5.jpg)

**Comment by ThomasEmge** [comment]
Unfortunately my results looked slightly different yesterday.

I think I found the issue - please give the updated files a try on the smaller data before attempting it on Italy.

**Comment by mboeringa** [comment]
@ThomasEmge , I now used the latest build to load Berlin again. No crash at the first two runs, so this looks promising. The results look as the one above, see the image. However, I noticed for the two buildings pointed out by the red arrows, that the outer way is still included in the Feature Class? So we still have the problem of the outer way not being removed:

![bode_museum_build2](https://cloud.githubusercontent.com/assets/7635726/17590386/e561c874-5fd9-11e6-9daa-bc0172ac15f1.jpg)

Looking at the most left object on the OpenStreetMap website (http://www.openstreetmap.org/relation/1722769), I don't see anything special in the tagging: just the typical "outer has tags, but not on the relationship", so tag transfer must and does take place. The outer should be ditched here.

By the way, the building in the lower right (Altes Museum) near the blue arrow may look like a similar case, however, I detected some errors in the tagging, and have corrected them. It should now be made into a proper geometry.

**Comment by mboeringa** [comment]
Still experiencing random crashes, about 1 in 3 to 4 runs results in ArcMap unexpectedly closing, the other runs finish OK. All with the same settings...

Almost like if there is some counter keeping track of the number of cores being used / set in the environment settings, and crashing once in each X runs similar to the number of processes. But I guess this is coincidence...

**Comment by mboeringa** [comment]
@ThomasEmge 

It seems finally some good news: no more crashes! I have run the tool probably a dozen times against the Berlin dataset. Rock solid, not a single crash. I noticed some of the changes seem related to the clean up of the temporary osm files and geodatabase if I interpret the code changes well. Anyway, I also verified that the temporary data is being properly deleted after finishing the load, so this looks good as well.

However, we are not there yet: I see three remaining issues:

- With the latest build, if there are existing Feature Classes from a previous run, so the destination geodatabase isn't empty, I now end up with an empty Polygon and Polyline Feature Class, both **have no records**. So the data doesn't get properly overwritten. Any subsequent attempt to import to this particular geodatabase also failed in the same manner. Only be closing ArcMap, and deleting the geodatabase via Windows Explorer, was I able to properly import again in a new geodatabase. Trying to delete the geodatabase from ArcMap's catalog window failed. Although I did not get an error, the folder lost its "geodatabase icon" and subsequently showed up as a normal folder icon with ".gdb" extension (which is empty when I look in Windows Explorer)... So the geodatabase seems corrupted after importing with existing Feature Classes. I was able to reproduce this particular issue, so I am pretty sure of it.

- The issue of the outer way and multipolygon both being added to the output Feature Class when tag transfer has taken place, as I remarked in this post https://github.com/Esri/arcgis-osm-editor/issues/145#issuecomment-239164256, is still there. I get the same output as the image you see in that post, so the particular selected features in the shown image, are still present. This is not an "edge" case, rather the classic example of where tag transfer needs to take place: no tags on the multipolygon, while the outer contains the information.

- I am not sure if this is actually by design and needs to stay like this, but I noticed it at least appears that some processes are being run twice. E.g. notice the osmID_IDX indexing processes appearing twice for the Polyline and Polygon Feature Classes. Also the Repair Geometry step seems duplicated, although there may be sense in that last thing considering the dirty source data...

![loader_issue_processes_appear_twice](https://cloud.githubusercontent.com/assets/7635726/17642916/e15e379a-6159-11e6-95b3-921b8730217a.jpg)

**Comment by ThomasEmge** [comment]
The first item you mention looks like a database locking issue - that needs to be checked. The second issue should not occur, you might be hitting the edge case I mentioned but my guess is that it is related to the schema lock issue in the first bullet item.
The third bullet item seems to be a reporting issue when the process is run in the foreground. At that point it seems that the core geoprocessing framework is showing the messages when I am programmatically executing the tool and then the osm tool is reporting the results of the programmatic code execution. I'll check if I there is a way around the double reporting but it is just that. The tool executes only once and the double reporting does not happen when the tool is run as a background process.

**Comment by mboeringa** [comment]
> The tool executes only once and the double reporting does not happen when the tool is run as a background process.

OK, I just noticed it and thought it wise to report it. No big deal this particular issue. Of course, especially the unsolved second issue has my main attention, as that is the main remaining big issue.

**Comment by ThomasEmge** [comment]
It was a locking issue when multiple loading processes are involved. Please give the updated version a try.

**Comment by mboeringa** [comment]
I'll do and report back.

**Comment by mboeringa** [comment]
@ThomasEmge ,

The problems still do not seem fully solved when running in 32-bit foreground processing (that is the only thing I currently tested, haven't had time for the background processing). I still get the empty FCs after one or two runs). Also, the outer way issue is not yet solved.

There are two new things I noticed though:

- When the processes of loading is finished, and I look in the File Geodatabase folder, I see this:

![lock_on_point_feature_class](https://cloud.githubusercontent.com/assets/7635726/17754908/32bf02e2-64d7-11e6-8bd5-8d91ca8b01d4.jpg)

Notice the lock that I pointed out. I named the Point feature class "PT", so its still holding a lock on it. Even when I delete all three feature classes from ArcMap's catalog window, does this "PT" linked lock file stay. I guess it shouldn't, and seems directly related to all you wrote.

- I noticed a message in the progress dialog stating something like "Adding Output to Map". However, this has never happened to me with the new tool. I always need to manually load them using the catalog window.

Marco

**Comment by mboeringa** [comment]
@ThomasEmge,

Well, congratulations! You've finally managed to crack this hard nut of getting this advanced multiprocessing option of the OSM File Loader (Load only) tool running reliable! This was one ordeal..., but well worth all the effort!...

Attached the result of the Berlin museum quarter, both just the building polygons as shown before, and as full rendered data... This now looks OK. The buildings that did not have their outer way removed in favour of the multipolygon relation, are now being properly processed and the outer is dropped, you can see it because the inner courts are now longer filled up by the second outer way polygon. I also do not see any remaining lock files in the geodatabase folder, and can overwrite the data without issues.

The performance of the this multi-processing loader, even on a limited four core machine like mine, is quite impressive. I think it now rivals osm2pgsql, or at least comes much closer. Loading the Netherlands, with over 100M nodes, 13.6M ways and just over 100k relations based on the 1.5GB bz2 zipped file (25GB uncompressed) from Geofabrik, took just under 17 hours using 3 cores (I didn't want to make my computer unusable by consuming all four cores for the task). This is with the unavoidable technical limit of the need to do single core table Append and Index operations, as these processes can't be run in multiprocessing mode. This is all much faster than the Load OSM File tool (that of course still has its own place with the full relation loading capacity as necessary for the e.g. the network functionality), that probably took some 5 days to process the same Netherlands file...

It is one wonderful tool to have for rendering OSM data in ArcGIS!

Anyway, there is just one minor issue, not bug, you may consider:

- In noticed that somewhere during the relations processing, which seems largely a single process/core job, that ArcMap appears to hang, with a "not responding" in the Windows Task Manager and no ability to refresh or activate the ArcMap window by clicking on it or the status bar's representation of the process. Note that this is with 32 bit foreground processing. It eventually finishes fine, but maybe it would be good to include some activity / progress indication at this stage of the processing, so as to allow ArcMap's interface to occasionally be refreshed / accessible. Having a "not responding" ArcMap may lead people doing giant imports (for which this tool is designed) to falsely belief the process failed, and maybe even prematurely kill the process while its still going on fine.

Lastly, I will keep an eye out for further issues, but for now, this really looks OK and hence I will close the outstanding issues I submitted.

![final_result_multiprocessing](https://cloud.githubusercontent.com/assets/7635726/17837788/ffb226d4-67bc-11e6-9c2e-b3eb097e5106.jpg)

![final_result_multiprocessing_rendered](https://cloud.githubusercontent.com/assets/7635726/17837794/07d8b03a-67bd-11e6-919b-f16c5f59a534.jpg)

**Comment by ThomasEmge** [comment]
Good to hear it is working now. There is one item left I would like you to observe. 
As you are working with larger datasets, like country size, please every now and then do take a look if you have a long running loading (python) process. By that I mean if you set the parallel processing factor to a number, let's say 4, is there a python process that runs significantly longer (in the order of hours)? 
Every now and then I have noticed such a process but I wasn't really able to reliably reproduce it. Just keep an eye on it and let's us know.

**Comment by mboeringa** [comment]
> By that I mean if you set the parallel processing factor to a number, let's say 4, is there a python process that runs significantly longer (in the order of hours)?
> Every now and then I have noticed such a process but I wasn't really able to reliably reproduce it. Just keep an eye on it and let's us know.

Well, I can confirm that the individual Python processes do not all finish at the same time. But as I just started exploring larger datasets, and finished loading the Netherlands, 

My first reaction and guess was that this simply has to do with the data complexity. If one of these process needs to deal with excessively large or complex features, having a difference of couple of hours on a process that still may take one or a few days, wouldn't be that surprising.

Since I guess you split up and load the databases simply based on X-number of XML records, and I have seen that data in osm XML files is actually quite spatially clustered (think building imports as cause!), it would be entirely logical for some sections with for example high quality / detailed imports for a municipalities, to be far more complex in loading than others. This would  certainly be able to explain a "couple of hours" of difference on a loading process taking e.g. 1 or 2 days.

Now if you assigned the XML records randomly to each process / sub-geodatabase, then it would be more of a surprise to see marked differences on large data extracts. But I doubt you do that, nor that it would be wise, because the clustering is probably a good thing in terms of database performance.
