### ISSUE TITLE
load OSM file doesn't work

### ISSUE THREAD

**Issue by miamichal** [Esri/arcgis-osm-editor#147]
arcgis version 10.41, 
Messages
Executing: OSMGPFileLoader "F:\pulpit3\praca magisterska\asd\map.osm" CONSERVE_MEMORY ALL "F:\pulpit3\praca magisterska\asd\test.gdb\test1" "F:\pulpit3\praca magisterska\asd\test.gdb\test1\test1_osm_pt" "F:\pulpit3\praca magisterska\asd\test.gdb\test1\test1_osm_ln" "F:\pulpit3\praca magisterska\asd\test.gdb\test1\test1_osm_ply"
Start Time: Tue Aug 23 12:32:47 2016
Counting elements in OSM file...
Counted 499376 nodes, 72683 ways, and 1488 relations.
**Unable to locate the osm_domains.xml (domain configurations) file.
Failed to execute (OSMGPFileLoader).**
Failed at Tue Aug 23 12:32:55 2016 (Elapsed Time: 8.66 seconds)

**Comment by ThomasEmge** [comment]
If you run into this error you need to manually point the tool (and your geoprocessing environment) to the location of the files.
If not already open, please open your Editor toolbar by using the following menus Customize > Toolbars > Editor.

![editortoolbar](https://cloud.githubusercontent.com/assets/1569501/17901131/ef3617f6-6916-11e6-97bc-83dceae2e8ff.PNG)

Then open the Options menu entry 

![editoroptions](https://cloud.githubusercontent.com/assets/1569501/17901158/122782c2-6917-11e6-9b06-dce3fa8bd89b.PNG)

In the opening dialog select the tab that has OpenStreetMap in the title. I am suspecting that either all or some text boxes are empty. Please click the Select button next to the empty text box and navigate to your installation directory. If you accepted all the defaults during the install process it should be something like C:\Program Files (x86)\ESRI\OSMEditor\Bin.

![configurationfiles](https://cloud.githubusercontent.com/assets/1569501/17901547/bc6c7c82-6918-11e6-8cc4-0e0ba319a977.PNG)

With the information filled out, the dialog page should look similar to the following outline

![fillededitoroptions](https://cloud.githubusercontent.com/assets/1569501/17901588/ea4fb39e-6918-11e6-8b43-699d7c992b38.PNG)

Accept the entered information and close the dialog by clicking the OK button, and then restart ArcMap to read the new configuration files.

**Comment by miamichal** [comment]
Okay, thanks. It worked out.
