### ISSUE TITLE
Missing "Repair Geometry" step in OSM File Loader (Load only) tool

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#149]
Hi @ThomasEmge ,

I have now attempted to load both the Netherlands and Denmark with the latest build of the OSM File Loader. However, when I rendered the data, I noticed issues with the display of some of the Polygon geometries in the Denmark dataset.

I then ran the Repair Geometry tool against the data, and this revealed close to 10000 faulty geometries on the Denmark dataset, primarily, but not exclusively, "ring order issues". The latter not surprisingly, as they directly relate to the non-compulsory ring order in OSM datasets and multipolygons or closed ways defined as "area" via the area key. I don't know yet how many geometries are bad in the Netherlands import, because the Repair Geometry step is only half way, but I do some issues listed in the progress dialog (which only shows a fraction, the rest is written to a text file at the end of the process).

Did you accidentally comment out a Repair Geometry step in the latest build, that needs to be activated again?

**Comment by ThomasEmge** [comment]
The step is still in there, but one of the helper classes had expired.

**Comment by mboeringa** [comment]
OK, thanks, I'll close this then.
