### ISSUE TITLE
OSM File Loader and multiprocessing trigger multiple Authorization Expiration messages

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#156]
Hi @ThomasEmge,

Again a rare corner case that is actually probably an ArcGIS core issue, and not a Loader issue, but I thought I would report it anyway.

Since my subscription for ArcGIS was near to its end, I now noticed the OSM File Loader's multiprocessing steps trigger multiple Authorization Expiration messages, one for each process spawned. So, as you can see in the screenshot below, when I set 4 cores in the geoprocessing environment settings, 4 warning boxes pop-up.

This is not really a big deal, because fortunately, the pop-ups / expiration messages are being closed automatically during the loading process once the python.exe processes are shut down upon finishing a multiprocessing step.

Still, this is mildly annoying behaviour. In case someone runs a hefty XEON workstation with potentially something like 24 cores, it is not unthinkable they will set the multiprocessing factor to 24 as well and get 24 pop-ups.

I guess this - likely ArcGIS core - issue is already known with ESRI and registered, so there is probably nothing to do for you here, but it is good to be aware of it.

![expiration_messages](https://cloud.githubusercontent.com/assets/7635726/18618698/3702a9ac-7dec-11e6-8551-47b476b9d33d.jpg)

**Comment by ThomasEmge** [comment]
Yes, this is core behavior. You can disable the warning by using the AdvancedArcMapSettings.exe application in the Desktop10.4\Utilities installation folder. Choose the Miscellaneous tab and uncheck the license warning on the bottom of the dialog.
