### ISSUE TITLE
Should ESRI run its own XAPI / Overpass API server?

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#157]
Hi @cloveman, @eggwhites and @ThomasEmge ,

This is a question that has been creeping up to me lately, especially with the recent service disruption of the main German (X)API instance caused by over-usage of some mobile App.

Now with a potential upcoming new release of the Editor toolbox, and especially the revamped and bug-fixed **OSM File Loader (load only)** tool combined with the **Download OSM Data (XAPI)** tool, it is clear ESRI will provide some real powertools for downloading and converting of OSM data to user friendly ArcGIS formats for e.g. cartography and analysis.

While some people will download entire country extracts from e.g. Geofabrik, it is likely many people will want to use the **Download OSM Data (XAPI)** tool to download custom extents of data for their region on the globe. With a large pool of power GIS users in ESRI's customer base, I can imagine that putting serious strain on the free third party services that provide the (X)API endpoints. Now the amount of data downloadable data from the (X)API, according to this page:

http://wiki.openstreetmap.org/wiki/Overpass_API

seems fairly liberal, but I still wonder if this could potentially result in heavy usage by ESRI customers (including myself here ;-)) at some point in time, and system administrators deciding it is over-usage. I also have the feeling from some other stuff I read, that large rather infrequent batch requests of data - which is a likely usage pattern for the ESRI tools - are far less of a problem than very frequent small requests like a potential mobile App, but still, it may be good to think about this. 

It would be really sad to see ESRI users being limited or shut out because of over-use of existing infrastructure. If ESRI had its own copy of an XAPI server the Download OSM Data (XAPI) server could point to, this would be far less of a problem.

I have zero experience with all of this, so can't be of any help here, but I would be interested to hear the views of ESRI on this...

Also see this Wiki page with more info about OSM XAPI:
http://wiki.openstreetmap.org/wiki/Xapi

**Comment by cloveman** [comment]
We do have an internal overpass server setup for demos and prototypes…and we have discussed the value in doing something like you suggest for those reasons you’ve outlined, but no current plans.

**Comment by mboeringa** [comment]
Hi @cloveman ,

Thanks for response. Yes, I guess it was logical ESRI already considered this. I assume ESRI has intermittent but regular contact with the OSMF, so in the rare case if any problems would come up due to usage, there is a channel for that... I am not a member of the OSMF myself (yet), nor have I attended the SOTM meetings, so just get my limited info from the internet.

**Comment by mmd-osm** [comment]
@mboeringa : OSMF is clearly not the right channel for this, see https://lists.openstreetmap.org/pipermail/talk/2016-September/076825.html

**Comment by mboeringa** [comment]
@mmd-osm , thanks for the info, but I don't work for ESRI. I am just an experienced ArcGIS product user and programmer, and have helped out with some of the testing of the toolbox maintained in this Open Source repository.

It will be up to @cloveman to potentially act on this.
