### ISSUE TITLE
Switch default for supporting nodes in OSM File Loader (Load only) tool

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#158]
Hi @ThomasEmge,

Currently, the **OSM File Loader (Load only)** tool has the "Delete supporting nodes" option set to **false** by default.

Considering there is little to no use for nodes without tags, and maintaining them just bloats the resulting geodatabase, I suggest to set this parameter to **true** as default, so supporting nodes are dropped.

**Comment by ThomasEmge** [comment]
My thinking here was for timing reasons. Deleting the nodes than can take a while for larger import.

**Comment by mboeringa** [comment]
From what I have seen up to now, the time needed is not to bad - although admittedly not insignificant either - but all in all, I feel the balance is in favour of deleting them by default considering the benefits of a lean and uncluttered geodatabase.
