### ISSUE TITLE
Attempt to append data created with OSM tool results in missing/incorrect nodes

### ISSUE THREAD

**Issue by eggwhites** [Esri/arcgis-osm-editor#16]
Steps to replicate:
1) Create a dataset using the OSM Toolbox - e.g., create a geodatabase and populate it with features through the OSM Server Component

2) Follow workflows for importing, per documentation at https://github.com/Esri/arcgis-osm-editor/wiki/Contribute-an-existing-dataset-to-osm

3) At Append step, node IDs are getting mixed up. Consequence: errors such as the one below result when Upload not successful; when Upload is successful, nodes and polygons are placed in incorrect locations on the map.

"The remote server returned an error: (412) Precondition Failed.
Precondition failed: Way  requires the nodes with id in (7308,7309,7310,7311), which either do not exist, or are not visible...."

**Comment by ThomasEmge** [comment]
Unable to reproduce. I appended some line features to existing edits and uploaded everything. Seems ok.

Christine, if this is still an issue we can re-open the issue.
