### ISSUE TITLE
Load OSM file (Version 10.4x64)

### ISSUE THREAD

**Issue by rvhgaea** [Esri/arcgis-osm-editor#161]
The tool Load OSM file seems to work until you open the filegeodatabase, which is empty.

Added : the same results with the tool  OSM File Loader (Load only)

![result](https://cloud.githubusercontent.com/assets/16819314/19964124/3ef6c330-a1c0-11e6-96b1-62d0909ccec0.png)

Version used : OSM 10.4x64 on ArcMap 10.4.1

Am I doing something wrong or is the tool not working properly?

Regards,

Robert

**Comment by ThomasEmge** [comment]
The tool can't find any elements in the OSM file as the counting elements line doesn't report any nodes, ways, or numbers. How did you generate the OSM file?

**Comment by rvhgaea** [comment]
I have examined the file and indeed it is empty. It gave an error message that it ren out of memory. The file itself was downloaded from OSM after making a selection.  I have to say that this very strange. I will try another file and look what it does. Thank you for your reply. I will give an update later.

**Comment by rvhgaea** [comment]
The export button on the OSM website results momentarily in an webpage error, I don't if it is related. Via the Overpass API I could download a file, which was imported successfully. So the error seems to be the file and not the tool.

Thanks again!

**Comment by mboeringa** [comment]
Be aware that even using the Overpass API, there may at times, and especially with larger extracts, be query time-outs, meaning the produced XML file is incomplete. AFAIK Overpass API has some limits set on the maximum amount of RAM a query may consume, and also the time a query may run, so as to avoid using up the entire servers resources by a single user.

For country size extents, it is best to download an extract from Geofabrik, where you can easily select your country:
http://www.geofabrik.de/

**Comment by skmoore** [comment]
@cloveman

**Comment by rvhgaea** [comment]
Thank you all for your replies and insights. It was very useful for me!
