### ISSUE TITLE
Load OSM File Error (version 103x64)

### ISSUE THREAD

**Issue by bkgelder** [Esri/arcgis-osm-editor#163]
I just installed ArcGIS Editor for OSM 10.3.x 64 bit version (had installed 32 bit first then uninstalled and reinstalled 64) and got an issue when trying to use 'Load OSM File' tool. It gives an error 'Unable to locate the osm_domains.xml (domain configurations) file.'. It seems that the 64 bit install either installs the file in the wrong location or looks for it in the wrong location. I copied the file to C:\Program Files\ESRI\OSMEditor\Bin after I found it in the 32 bit analogue spot, C:\Program Files (x86)\ESRI\OSMEditor\Bin 

I figured this out after finding this similar issue (closed, but it doesn't seem to be resolved):
https://github.com/Esri/arcgis-osm-editor/issues/54

**Comment by ThomasEmge** [comment]
The first time you run the tools a config file is generated in _<UserProfile>/AppData/Roaming/Esri/OSMEditor_ storing amongst other things the location on where to find the find the files. Uninstalling the 32bit and reinstalling the 64bit version unfortunately doesn't auto-generate an update. 
Either you manually delete the file and a new file will be generated for you (hopefully containing the corrects paths) or you can use the Editor > Editor Options... dialog and the OpenStreetMap tab to update the file locations to the current 64bit locations.
