### ISSUE TITLE
OSM-Editor for 10.5

### ISSUE THREAD

**Issue by sdieball** [Esri/arcgis-osm-editor#166]
Do you plan to have a version for ArcGIS 10.5?
And do you have a rough schedule when this might be the case?
Thanks.
Stefan

**Comment by cloveman** [comment]
Testing is complete, we will be packaging up the install and posting to ArcGIS Online/Github in the next week or so.

**Comment by sdieball** [comment]
Thanks for your reply and for your work. So I won't go back to 10.4.
