### ISSUE TITLE
10.1 64 Bit on osmtest - Properties for OSMFeatureProperties.xml file can never be set

### ISSUE THREAD

**Issue by eggwhites** [Esri/arcgis-osm-editor#17]
Steps to replicate:
Launch ArcMap with OSM Editor for 64 Bit Geoprocessing installed.

Click on Editor toolbar, and select Properties.

Go to OpenStreetMap tab.

The setting for OSMFeatureProperties.xml file (the last on the page) is not populated. When attempt to populate, click Apply, click OK, and then reopen, the file mapping is not persisted. Closing and reopening ArcMap doesn't make a difference.

**Comment by ThomasEmge** [comment]
Fixed with https://github.com/Esri/arcgis-osm-editor/commit/09356f40f00ec7896900daf075e3a8e59ada21cb#diff-25d902c24283ab8cfbac54dfa101ad31
