### ISSUE TITLE
Load OSM File doesn't load Attributes

### ISSUE THREAD

**Issue by mmarzgis** [Esri/arcgis-osm-editor#171]
Hello!
I want to load and extract all features regarding osm tags with "addr". For this purpose, I use "Load OSM File" and select "ALL" at "Add OSM tag keys to schema". 
The result are different features with long attribut tables, but with no records. 

Is there anything wring with my workflow?

**Comment by ThomasEmge** [comment]
Nothing wrong with the workflow. However as the tool mentions it is preparing the schema. You still need to run the "OSM Attribute Selector" tool to extract the "addr" attribute from BLOB field storing all the attributes.
In your case, you would combine the "Load OSM File" and the "OSM Attribute Selector" tools into a model and then execute the model. The model approach offers more flexibility for different user needs.
