### ISSUE TITLE
OSM File Loader (Load Only) fails on Netherlands extract

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#175]
Hi Thomas,

I don't know what changed in my setup, besides the regular Windows updates, but I now get a failure to load the Netherlands extract of Geofabrik. I have loaded this extract multiple times over the past years, and never got this kind of failure.

I attempted it with both 64 bit background geoprocessing enabled, and disabled, both fail at the same point, when loading of ways needs to start. It appears the Python processes, which seem to have already been initiated, still wait for some response from ArcMap before they can continue. The processes simply do not continue beyond this stage, even after waiting hours. If I kill ArcMap using the Task Manager, the intiated Python processes DO start to run. See the attached images explaining the situation.

- First image. Notice how the geoprocessing dialog shows the process having finished Node loading, and started Ways loading. Despite this, both ArcMap and the Python processes launched, are at 0% processor activity (next images).

![geoprocessing dialog](https://user-images.githubusercontent.com/7635726/28238427-6bdf5c62-6953-11e7-99c4-c97fba6d1a5c.jpg)

- Processor activity for the ArcMap application and the launched Python processes is 0%:

![task_manager_arcmap_process](https://user-images.githubusercontent.com/7635726/28238435-91257326-6953-11e7-95f0-3dc7c436cb55.jpg)

![task_manager_python_processes](https://user-images.githubusercontent.com/7635726/28238437-957bad14-6953-11e7-8fa2-63890d6efe74.jpg)

- The Explorer shows that the temporary File Geodatabases for e.g. the Nodes, have been properly deleted:

![explorer_gdbs](https://user-images.githubusercontent.com/7635726/28238455-cf3631dc-6953-11e7-8c12-18d6e6c142c0.jpg)

- Also temporary *.osm files seem properly updated for this stage of the processing, with the nodes files deleted:

![explorer_osm_files](https://user-images.githubusercontent.com/7635726/28238459-ed226a76-6953-11e7-85c6-edc690c88a03.jpg)

- When I kill the ArcMap application, the Python processes finally start to run:

![task_manager_python_processes_after_arcmap_kill](https://user-images.githubusercontent.com/7635726/28238479-b5dac13e-6954-11e7-8c9b-24050f886114.jpg)

**Comment by ThomasEmge** [comment]
Marco, not sure what or why it would happen. I have used the tools over the past two weeks on a non-developer machine without any issues.
From your screen captures it looks like the order of processing is working as expected. I don't expect any issues coming from the OS updates, as the python modules seem to be starting just fine. 
I am tending towards some locking issues as there seems to be a dependence on ArcMap. How many ArcMap/ArcCatalog instances do you have running when this happens?

**Comment by mboeringa** [comment]
@ThomasEmge , could this potentially be caused by some firewall restriction on Python, where the Python processes can't communicate with ArcMap, while they can obviously be launched as the processes are visible in the Task Manager?

I am asking because I have seen Windows putting restrictions on Python automatically and warning about this. That never seemed to affect the running of the import process though, but I don't know if some Windows update set some new restriction.

Or is this unlikely or impossible considering the particular point of failure?

**Comment by mboeringa** [comment]
> I am tending towards some locking issues as there seems to be a dependence on ArcMap. How many ArcMap/ArcCatalog instances do you have running when this happens?

My last runs were with just a single ArcMap session open to prevent such possible locking issues. I also made sure all other Python and ArcMap session were killed using the Task Manager before attempting another import, or rebooted.

**Comment by ThomasEmge** [comment]
Hmm, there goes the locking idea. I don't think it is a firewall issue as Python is only asking for a file on disk. Nothing really leaves the computer or establishes a connection with an outside service. Even if i:\ drive is on a network, it worked for the points/nodes.
Have you tried to write the points, lines, and polygons into different (separate) file geodatabases? I wondering if there are some other resources being exhausted.

**Comment by mboeringa** [comment]
@ThomasEmge , I also see this issue now with the import of a small dataset. There's plenty of free RAM and disk space.

I have now tested the import of the small Bosnia Geofabrik extract again that also failed, and it again got stuck. I do see one lock file inside the File Geodatabase. If I look in Windows Source Control as opened from the Task Manager, I see this single lock file having the same Process ID (PID) as the ArcMap session I used to import the data. So only the ArcMap session that initiated the import, seems to hold a lock on the File Geodatabase during the import and the particular stage it is failing.

I guess this lock should be there and is entirely normal, as ArcMap is using the File Geodatabase, so there doesn't seem anything wrong here... No other "lock" files are in the File Geodatabase folder.

**Comment by mboeringa** [comment]
By the way, if instead of killing the ArcMap process, I kill the spawned Python processes, the progress dialog in ArcMap happily reports success for the step, and continues with the next step (that again gets stuck once the Python processes appear in the Task Manager). If I keep killing each spawned Python process, I eventually end up with a "Succeeded" message at the end of the tool run, with no apparent errors being displayed...
