### ISSUE TITLE
Failed to execute (OSMGPCreateNetworkDataset).

### ISSUE THREAD

**Issue by rgardnercook** [Esri/arcgis-osm-editor#182]
Hello,
I am trying to create a network dataset from OSM data for New York City. I've followed the instructions from the wiki and used the Load OSM File tool. When I move on to the Create OSM Dataset tool (with the DriveGeneric network config file) I get the following messages:

Messages
Executing: OSMGPCreateNetworkDataset "J:\new-york_new-york.osm\New File Geodatabase.gdb\NYC_OSM_features" "C:\Program Files (x86)\ArcGIS\Desktop10.5\ArcToolbox\Toolboxes\ND_ConfigFiles\DriveGeneric.xml" "J:\new-york_new-york.osm\New File Geodatabase.gdb\NYC_OSM_features\NYC_OSM_features_nd"
Start Time: Wed Dec 20 09:50:18 2017

Extracting Edge Features

Select_analysis

Extracting Junction Features

Select_analysis

Assigning Network Connectivity Groups

Extracting Turn Restrictions

CreateTurnFeatureClass_na

AddField_management

Populating Turn Features from OSM Relations

The row contains a bad value. [RestrictionType]
   at ESRI.ArcGIS.Geodatabase.IFeature.Store()

   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkTurns.CreateTurnFeature_NO(TurnFeatureClassWrapper turnFCW, OSMTurnInfo osmTurn)

   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkTurns.PopulateTurnsFromRelations()

   at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)

   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkTurns.ExtractTurnRestrictions()

   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.ExtractTurnRestrictions()

   at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)

   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateNetworkDataset()

   at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
Failed to execute (OSMGPCreateNetworkDataset).
Failed at Wed Dec 20 10:59:32 2017 (Elapsed Time: 1 hours 9 minutes 13 seconds)

How can I get around this? I should note that I'm running this with foreground processing and 64 bit. I got a different error with background processing (Error HRESULT E_FAIL has been returned from a call to a COM component).

Thank you!

**Comment by mboeringa** [comment]
@rgardnercook , did you solve this issue? If not, it might be helpful for the ESRI people here if you could share a Map Package with the data and the results of the Load OSM File tool.

Also, what was the source of your osm *.xml file that you fed to the Load OSM File tool? If it is some custom extraction of only highways, not a Geofabrik or QGIS full download of all data, I guess some stuff to create the network might be missing, although I think it unlikely it would fail after 1 hour in that case, instead of much sooner. Actually, the error message ("The row contains a bad value. [RestrictionType]"), seems more to indicate some unknown value in a specific row / field, that is apparently not properly handled by the code.

By the way, I am slightly puzzled by the file path you are showing, which has the resulting File Geodatabase in a path with the osm *.xml filename and *.osm file extension. Maybe benign, but something to probably avoid. ( "J:\new-york_new-york.**osm**\New File Geodatabase.gdb\NYC_OSM_features")

**Comment by rgardnercook** [comment]
@mboeringa , thanks for the response. I was away from the office for an extended period of time. Now I'm on a new workstation, and starting this from scratch.

On this new workstation, Load OSM didn't work, spitting out the error I posted below here. I'm going to try the Download tool rather than use the .osm file I have. Perhaps that will solve all these issues!
Executing: OSMGPFileLoader "S:\~ArcMap Network Dataset for NYC\new-york_new-york.osm" CONSERVE_MEMORY ALL "S:\~ArcMap Network Dataset for NYC\OSM_NYC" "S:\~ArcMap Network Dataset for NYC\OSM_NYC\OSM_NYC_osm_pt" "S:\~ArcMap Network Dataset for NYC\OSM_NYC\OSM_NYC_osm_ln" "S:\~ArcMap Network Dataset for NYC\OSM_NYC\OSM_NYC_osm_ply" 

Start Time: Tue Apr 17 10:21:08 2018 

Counting elements in OSM file... 

Counted 11637914 nodes, 1825722 ways, and 10531 relations. 

Preparing geodatabase... 

Object reference not set to an instance of an object. 

   at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPFileLoader.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message) 

Failed to execute (OSMGPFileLoader). 

Failed at Tue Apr 17 10:24:27 2018 (Elapsed Time: 3 minutes 18 seconds)

**Comment by chenna997** [comment]
I have the exactly the same issue like you:
Populating Turn Features from OSM Relations

The row contains a bad value. [RestrictionType]

Did you fix this issue?

Thanks,

--Na

**Comment by rgardnercook** [comment]
Unfortunately, no. I ended up getting a completed network dataset from
someone else at work. I'd still like to figure it out in case I need to
build it again from scratch.

Good luck!

**Comment by chenna997** [comment]
Thanks for the response.
I am also still working on that. I will update with you if I can get it
fixed.

--Na

**Comment by ThomasEmge** [comment]
Fixed with #201
