### ISSUE TITLE
ArcGIS Desktop 10.6

### ISSUE THREAD

**Issue by StevePage-TT** [Esri/arcgis-osm-editor#184]
Hi, Apologies if I am off track here - this is my first use of GitHub.

I just downloaded the 'ArcGIS Editor for OSM release for 10.6' from here.
When I extract, it contains installers for Arc 10.1 only.
Try and run and advises 'only for 10.1'
I get the same issue with 10.5 release

Also noted that the download is many times larger file than the 10.5 installer downloaded from Esri website. They do not have the 10.6 installer available yet.

Thanks,

Steve

**Comment by scw** [comment]
@StevePage-TT The releases here are the source releases, I think you'll want to try [this download from ArcGIS Online](http://www.arcgis.com/home/item.html?id=0c4b24608fc94542ba5d1130c0606802).

Cheers, Shaun

**Comment by cloveman** [comment]
Our 10.6 install is now up at: https://www.arcgis.com/home/item.html?id=0c4b24608fc94542ba5d1130c0606802

**Comment by StevePage-TT** [comment]
Thanks scw and cloveman.
Note that the ESRI OSM Editor page still links to the ArcGIS 10.5 download page, with no advice that 10.6 is available.
I have posted this note there as well, but not sure who gets to fix this.
Thanks again, Steve

**Comment by scw** [comment]
@StevePage-TT thanks for the details. I've submitted a PR to get it added to the GitHub README, and I imagine it'll also go up on the main page soon.
