### ISSUE TITLE
Submitting 0 features to the server - ArcMap 10.5

### ISSUE THREAD

**Issue by wiuhighwayman** [Esri/arcgis-osm-editor#186]
I've been having issues getting created features submitted to OSM. I ran a test creating one polygon feature. Here are the steps:
Using Arc 10.5, MXD uses WGS1984
Ran Add OSM Editor Extension on all three OSM layers.
Began editing -- selecting the house feature in the polygon-building group layer
Created one new polygon (a house)
Saved edits
Uploaded, including the revision table (which was updated following editing). 
Received a successful upload message, but when I check the results, I get the following:
- Executing: OSMGPUpload http//www.openstreetmap.org "[full path]\EditTEST_osm_revision" "test upload - Sciota house" OSMCHANGE_FORMAT wiuhighwayman *****
- Start Time: Wed Jan 31 12:03:51 2018
- Opened changeset 55943436
- Submitting 0 features to the server...
- Reconciling local data with server information
- Closed changeset 55943436
- Succeeded at Wed Jan 31 13:06:52 2018 (Elapsed Time: 1.31 seconds)

A few additional attempts this process (doing different things, like editing an existing feature) resulted in "Submitting 0 features to the server" each time. I seem to be missing a step but haven't found anything in the documentation.

**Comment by ThomasEmge** [comment]
Please use [https://www.openstreetmap.org](https://www.openstreetmap.org) as the upload URL.
