### ISSUE TITLE
How to use OSM network dataset for a mobile map package

### ISSUE THREAD

**Issue by MuhammadYasirAlikhan** [Esri/arcgis-osm-editor#189]
I want to use network dataset created by running "Create OSM network dataset tool" using sample configuration file 'drive generic'. Is it possible to use that network dataset in a mobile map package using arcgis pro?

**Comment by ThomasEmge** [comment]
Muhammad,

the created network dataset is an item that is core to the ArcGIS platform and independent from the editor toolset. Personally I haven't tried it yet, but I don't see any technical reasons why this shouldn't work.

For more details on how to publish, please refer to the mobile map documentation at http://pro.arcgis.com/en/pro-app/help/sharing/overview/mobile-map-package.htm

**Comment by mboeringa** [comment]
Haven't tried this myself, but the Help pages dealing with your question seem these:

[Mobile map package](http://pro.arcgis.com/en/pro-app/help/sharing/overview/mobile-map-package.htm)

[Create Mobile Map Package](http://pro.arcgis.com/en/pro-app/tool-reference/data-management/create-mobile-map-package.htm#GUID-9116AC0F-08E1-4B55-965D-123F01262A53)

Especially the **Create Mobile Map Package** page seems relevant, as it contains a list of requirements for a network dataset in order for it to be valid for inclusion in a Mobile Map Package, see specifically the **Usage** section on that page.

**Comment by MuhammadYasirAlikhan** [comment]
I got the following problem. I m using sample configuration file "Drive Generic.xml"
"Start Time: Thursday, February 22, 2018 4:51:14 AM
 The network attribute [DriveTime] on the source [NZN_nd_roads] in the along digitized direction is a script evaluator.: Map/NZN_nd
 The network attribute [DriveTime] on the source [NZN_nd_roads] in the against digitized direction is a script evaluator.: Map/NZN_nd
 The network attribute [HeightRestriction] on the source [NZN_nd_roads] in the along digitized direction is a script evaluator.: Map/NZN_nd
 The network attribute [HeightRestriction] on the source [NZN_nd_roads] in the against digitized direction is a script evaluator.: Map/NZN_nd
 The network dataset does not have any travel modes defined.: Map/NZN_nd
 Failed to execute (CreateMobileMapPackage).
Failed at Thursday, February 22, 2018 4:51:15 AM (Elapsed Time: 0.71 seconds)"

**Comment by ThomasEmge** [comment]
Try to solve a route in ArcMap or Pro first. The desktop applications might provide more information about potentially missing information.
