### ISSUE TITLE
ArcGIS Editor for OpenStreetMap 10.6 (64-bit) Installer bug

### ISSUE THREAD

**Issue by CodyMarshESS** [Esri/arcgis-osm-editor#190]
Hello,

It seems that the silent installer for the setup.exe for the ArcGIS Editor for OpenStreetMap 10.6 (64-bit) is not present when running the installer from Powershell as SYSTEM. 

OS Tested: Windows 10 64-bit.
Installed ArcGIS products:
ArcGIS Desktop 10.6
ArcGIS Desktop 10.6 64-bit Background Geoprocessing

Steps to reproduce:

1. Download the ArcGIS Editor for OpenStreetMap 10.6 from the website: https://www.arcgis.com/home/item.html?id=0c4b24608fc94542ba5d1130c0606802
2. Open Powershell prompt as SYSTEM.
     * Download the folder found here: https://docs.microsoft.com/en-us/sysinternals/downloads/psexec
     * Run the following command in Powershell: **Start-Process -FilePath cmd.exe -Verb Runas -ArgumentList '/k <Folder_Location_from_previous_step>\PsExec.exe -i -s powershell.exe'**
3. Run the following command: <folder location_of_ ArcGIS_Editor_for_OpenStreetMap_10.6_(64-bit)>\setup.exe /s
4. The installer should immediately fail with the error: 
![image](https://user-images.githubusercontent.com/36715259/36509214-cd819692-1713-11e8-9e0c-752b117b03d2.png)

**Comment by robblis** [comment]
Hi,

To run a silent install, run the following command in a administrator command prompt.

<folder location_of_ ArcGIS_Editor_for_OpenStreetMap_10.6_(64-bit)>\setup.exe /s -v"/qn"
