### ISSUE TITLE
OSM File Loader tool causes coordinate shift

### ISSUE THREAD

**Issue by rvinogradov** [Esri/arcgis-osm-editor#200]
I've successfully loaded an .osm file as feature dataset in ArcMap using the **Load OSM File tool**. The problem I have now is that the generated output is not properly aligned with my basemap which has projection RD New. The tool seems to cause a visible shift in the coordinates of the final output OpenStreetMap lines. Normally this is easily fixed by using the Project tool to reproject the feature dataset to the desired coordinate system. However, according to the properties, the coordinate system of the feature classes created are already set to RD New, making it impossible to reproject the data. 

Any help would be more than welcome!

<img width="1257" alt="screenshot 2019-02-28 at 14 31 05" src="https://user-images.githubusercontent.com/40352112/53569979-a8214880-3b65-11e9-91d4-aefebee37fc1.png">
<img width="1254" alt="screenshot 2019-02-28 at 14 30 40" src="https://user-images.githubusercontent.com/40352112/53569980-a8b9df00-3b65-11e9-92fa-23ad6354ddfa.png">
<img width="1256" alt="screenshot 2019-02-28 at 14 30 13" src="https://user-images.githubusercontent.com/40352112/53569981-a8b9df00-3b65-11e9-9134-3551eac6e074.png">

**Comment by ThomasEmge** [comment]
What was the resolution? 

There is nothing really in the OSM tools that explicitly handles spatial references. The tools should be reacting to the settings in the geoprocessing environments. In other words, the default behaviour is to take the inputs as is and that is geographic WGS84. If a different spatial reference is set, then the inputs will be projected on-the-fly by the loader tool respecting the environment settings.
Reprojecting the original WGS84 downloaded dataset to your custom 'RD new' projection should take of the  shift.
