### ISSUE TITLE
Installer for ArcGIS 10.7

### ISSUE THREAD

**Issue by Chaz6** [Esri/arcgis-osm-editor#204]
I just purchased a personal subscription with the intent of using the Esri OSM tools, however I can only download ArcMap 10.7 and not any prior version! Please can you provide an installer ASAP :-)

**Comment by cloveman** [comment]
10.4:
https://www.arcgis.com/home/item.html?id=c18d3d0d5c62465db60f89225fdd2698

10.5:
https://www.arcgis.com/home/item.html?id=4533407decd94428817a228cb36964cf

10.6:
https://www.arcgis.com/home/item.html?id=0c4b24608fc94542ba5d1130c0606802

**Comment by Chaz6** [comment]
@cloveman I am not sure of the relevance of your comment? There is currently no installer for ArcMap 10.7.

**Comment by cloveman** [comment]
Ah...sorry misread. I thought you were asking for older version. We'll look to push out a 10.7 version soon.

**Comment by Chaz6** [comment]
@cloverman thank you!

**Comment by nskaprosy** [comment]
I would be interested in this as well. I am running into an error with the 10.6 version I am running on my older machine.

**Comment by skmoore** [comment]
@Chaz6 @nskaprosy The 10.7 installer is out: http://www.arcgis.com/home/item.html?id=e646719bc3284a3d9d81e02b3d5abc53

**Comment by nskaprosy** [comment]
Thank you Steve, I really appreciate your time and help!
