### ISSUE TITLE
Support for ArcGIS 10.8

### ISSUE THREAD

**Issue by Chaz6** [Esri/arcgis-osm-editor#211]
Please provide an installer for ArcGIS Desktop 10.8. Thanks!

**Comment by mboeringa** [comment]
Second that. Needs upgrading.

**Comment by mboeringa** [comment]
Through contact: ESRI is working on it.

**Comment by mboeringa** [comment]
@Chaz6 

You probably already saw it (I had missed it myself though), but a 10.8 version is now available:
https://www.arcgis.com/home/item.html?id=2f58a77a65c546149dd1ea425a680ad3

@ThomasEmge , shouldn't this issue be closed?

**Comment by Chaz6** [comment]
Thanks for the update!
