### ISSUE TITLE
Load OSM Diff Files

### ISSUE THREAD

**Issue by Jibrahn** [Esri/arcgis-osm-editor#218]
Good morning,

The Load OSM Diff Files download URL input has a validation issue that is preventing it from accepting valid URLs. The default URL, https://planet.openstreetmap.org/replication/, is marked as invalid.

This is using ArcMap 10.7.1.

**Comment by ThomasEmge** [comment]
I updated the code to switch to use the secure protocol. URL parameter validation does succeed now.
