### ISSUE TITLE
Loading Ways file creates empty layers with no features

### ISSUE THREAD

**Issue by Jibrahn** [Esri/arcgis-osm-editor#219]
I have .osm files from Overpass, and they are all Way elements. When I try importing them into ArcMap 10.7.1 with either OSM File Loader(Loader only), Load OSM File, or OSM Way Loader, I get empty layers with no features.  Here is a sample osm:

<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.56.3 eb200aeb">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2020-06-02T16:40:02Z" areas="2020-06-02T14:56:03Z"/>  <way id="30804" version="16" timestamp="2020-03-09T12:59:46Z" changeset="81964768" uid="1758654" user="JJJWegdam">
    <nd ref="249674024"/>
    <nd ref="3530749467"/>
    <tag k="alt_name" v="Chingford Branch Line"/>
    <tag k="electrified" v="contact_line"/>
    <tag k="frequency" v="50"/>
    <tag k="gauge" v="1435"/>
    <tag k="maxspeed" v="40 mph"/>
    <tag k="name" v="Lea Valley Lines"/>
    <tag k="oneway" v="yes"/>
    <tag k="operator" v="Network Rail"/>
    <tag k="railway" v="rail"/>
    <tag k="source" v="Survey of 2015-05-20"/>
    <tag k="tracks" v="2"/>
    <tag k="usage" v="branch"/>
    <tag k="voltage" v="25000"/>
  </way>
  <way id="2795857" version="10" timestamp="2020-03-09T12:59:46Z" changeset="81964768" uid="1758654" user="JJJWegdam">
    <nd ref="33102019"/>
    <nd ref="3747982644"/>
    <nd ref="1736723402"/>
    <nd ref="3747982654"/>
    <nd ref="1094034653"/>
    <nd ref="3747982663"/>
    <nd ref="1736723424"/>
    <nd ref="3747982670"/>
    <nd ref="12708022"/>
    <nd ref="3747982682"/>
    <nd ref="1736723454"/>
    <nd ref="3747982688"/>
    <nd ref="1736723459"/>
    <nd ref="3747982695"/>
    <nd ref="1736723465"/>
    <nd ref="12708023"/>
    <nd ref="1736723477"/>
    <nd ref="1736723480"/>
    <nd ref="12708024"/>
    <nd ref="1736723492"/>
    <tag k="electrified" v="contact_line"/>
    <tag k="frequency" v="50"/>
    <tag k="gauge" v="1435"/>
    <tag k="maxspeed" v="50 mph"/>
    <tag k="name" v="Lea Valley Lines"/>
    <tag k="railway" v="rail"/>
    <tag k="usage" v="branch"/>
    <tag k="voltage" v="25000"/>
  </way>
  <way id="2902802" version="16" timestamp="2020-03-09T12:59:46Z" changeset="81964768" uid="1758654" user="JJJWegdam">
    <nd ref="17019735"/>
    <nd ref="1783938001"/>
    <nd ref="1783938003"/>
    <nd ref="6135938651"/>
    <nd ref="1783938006"/>
    <nd ref="1783938008"/>
    <nd ref="1783938010"/>
    <nd ref="17019742"/>
    <nd ref="1783938013"/>
    <nd ref="1783938015"/>
    <nd ref="1783938016"/>
    <nd ref="17019746"/>
    <nd ref="1783938020"/>
    <nd ref="1783938022"/>
    <nd ref="2704408882"/>
    <nd ref="17019890"/>
    <nd ref="1783938032"/>
    <nd ref="28417035"/>
    <tag k="electrified" v="contact_line"/>
    <tag k="frequency" v="50"/>
    <tag k="gauge" v="1435"/>
    <tag k="maxspeed" v="60 mph"/>
    <tag k="railway" v="rail"/>
    <tag k="ref" v="HDT"/>
    <tag k="usage" v="branch"/>
    <tag k="voltage" v="25000"/>
  </way>
  <way id="3648973" version="38" timestamp="2020-02-29T14:42:41Z" changeset="81621768" uid="1758654" user="JJJWegdam">
    <nd ref="1270476281"/>
    <nd ref="1263352198"/>
    <nd ref="4292119302"/>
    <tag k="electrified" v="contact_line"/>
    <tag k="frequency" v="50"/>
    <tag k="gauge" v="1435"/>
    <tag k="layer" v="1"/>
    <tag k="level" v="1"/>
    <tag k="maxspeed" v="15 mph"/>
    <tag k="railway" v="rail"/>
    <tag k="railway:track_ref" v="1"/>
    <tag k="railway:traffic_mode" v="passenger"/>
    <tag k="ref" v="1"/>
    <tag k="tracks" v="1"/>
    <tag k="usage" v="main"/>
    <tag k="voltage" v="25000"/>
  </way>
  <way id="3649010" version="20" timestamp="2020-03-09T12:59:46Z" changeset="81964768" uid="1758654" user="JJJWegdam">
    <nd ref="25315751"/>
    <nd ref="1262682252"/>
    <nd ref="1262682763"/>
    <nd ref="1262682510"/>
    <nd ref="1262682594"/>
    <nd ref="80822825"/>
    <nd ref="1262682605"/>
    <nd ref="1262682573"/>
    <nd ref="18090798"/>
    <nd ref="1262682789"/>
    <nd ref="1262682484"/>
    <nd ref="1262682333"/>
    <nd ref="1262682786"/>
    <nd ref="18090797"/>
    <nd ref="244252280"/>
    <tag k="bridge" v="yes"/>
    <tag k="electrified" v="contact_line"/>
    <tag k="frequency" v="50"/>
    <tag k="gauge" v="1435"/>
    <tag k="layer" v="1"/>
    <tag k="loading_gauge" v="W10"/>
    <tag k="name" v="North London line"/>
    <tag k="railway" v="rail"/>
    <tag k="source" v="NPE"/>
    <tag k="usage" v="branch"/>
    <tag k="voltage" v="25000"/>
  </way>
</osm>

**Comment by Jibrahn** [comment]
[SampleWaysFile.txt](https://github.com/Esri/arcgis-osm-editor/files/4724163/SampleWaysFile.txt)

**Comment by ThomasEmge** [comment]
The sample file only contains the descriptions of the ways and it is missing the actual nodes (coordinates) that are needed to create the vertices for the lines.

**Comment by Jibrahn** [comment]
Thanks! I didn't realize the Overpass results were just descriptions.
