### ISSUE TITLE
Create OSM Network Dataset crashing

### ISSUE THREAD

**Issue by mhogeweg** [Esri/arcgis-osm-editor#225]
hi, on 10.8.1 trying to create a network dataset.
- downloaded OSM data (.osm file) using XAPI tool
- started Create OSM Network Dataset tool with the DriveMeters.xml as network configuration file
- process starts and runs until just after 'Creating Network Dataset' message
- then:

```
Exception from HRESULT: 0x80042288
   at ESRI.ArcGIS.Geodatabase.IDatasetContainer2.CreateDataset(IDEDataset DataElement)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateBuildableNDS()
   at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateNetworkDataset()
   at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
Failed to execute (OSMGPCreateNetworkDataset).
Failed at Wed Dec  9 12:39:39 2020 (Elapsed Time: 1 minutes 26 seconds)
```

any thoughts?

**Comment by ThomasEmge** [comment]
Hey Marten,

make sure that gp is running in the foreground.

Also, I am not sure if the XAPI endpoint are actively maintained. Usually I would recommend using our OSM Download gp tool to get an area of interest or grab an export from [https://download.geofabrik.de/](https://download.geofabrik.de/)

**Comment by mhogeweg** [comment]
download using XAPI worked fine. Other tools (Download OSM Data, Download, Extract, Symbolize OSM Data) also failed. Both with SSL/TLS errors:

```
Starting OSM Data download request...
The request was aborted: Could not create SSL/TLS secure channel.
Object reference not set to an instance of an object.
Failed to execute (OSMGPDownload).
Failed at Wed Dec  9 12:22:54 2020 (Elapsed Time: 1.59 seconds)
```

**Comment by mhogeweg** [comment]
turning off background GP did indeed resolve the network dataset issue.
