### ISSUE TITLE
Looking for a Multimodal Config File

### ISSUE THREAD

**Issue by MuhammadYasirAliKhan786** [Esri/arcgis-osm-editor#228]
Hello,
I want to create a multimodal network dataset from the .osm file using this tool but did not found the proper config file to create it. Is it possible to create a multimodal network dataset using the current sample config files? Or I have to manually create it after loading the osm file to ArcMap using "Load OSM File".
Thanks

**Comment by ThomasEmge** [comment]
Unfortunately, we do not have multimodal networks as part of the existing config files. 

Please use the ArcMap UI to create and build one for your needs and use case.
