### ISSUE TITLE
The tools is not valid

### ISSUE THREAD

**Issue by antodang100** [Esri/arcgis-osm-editor#229]
Hi I have Arcmap 10.8.1

And just download the tool for arcmap 10.8

But when i test run the tool its say tool is not vaild.

here is the error>

![image](https://user-images.githubusercontent.com/81360668/112461594-fbbbeb80-8d57-11eb-8a26-f605bd4d2002.png)

**Comment by ThomasEmge** [comment]
You have 2 options here. 
Option 1: Set your geoprocessing environment to execute the gp tools as a foreground process. For more detailed information, please read this doc https://desktop.arcgis.com/en/arcmap/latest/analyze/executing-tools/foreground-and-background-processing.htm
Option 2: Install the "ArcGIS Editor for OpenStreetMap 10.8 (64-bit)" version from the downloaded zip file.

**Comment by antodang100** [comment]
> You have 2 options here.
> Option 1: Set your geoprocessing environment to execute the gp tools as a foreground process. For more detailed information, please read this doc https://desktop.arcgis.com/en/arcmap/latest/analyze/executing-tools/foreground-and-background-processing.htm
> Option 2: Install the "ArcGIS Editor for OpenStreetMap 10.8 (64-bit)" version from the downloaded zip file.
