### ISSUE TITLE
During Download, extra layers are added to Table of Contents

### ISSUE THREAD

**Issue by eggwhites** [Esri/arcgis-osm-editor#35]
If you've checked the "Add results of geoprocessing functions to map" in the ArcMap Geoprocessing Options, then when you run the Download OSM Data; Download, Extract, and Symbolize OSM Data; or Load OSM File tools you will experience duplicate layers of your osm point, line, and polygon feature classes being added to your Table of Contents.

**Comment by ThomasEmge** [comment]
Anyone remember why this was flagged as a bug? The dataset and the three feature classes are output types so they should be added. The dataset itself will come in as a group layer (containing the three feature classes) and then the three feature classes themselves.
Is anyone with feature dataset as an output data type?

**Comment by ThomasEmge** [comment]
Works as designed. Let me know if you disagree and we'll re-open the discussion.
