### ISSUE TITLE
problem with only_straight_on turn restriction

### ISSUE THREAD

**Issue by paulcone** [Esri/arcgis-osm-editor#40]
I've loaded up OSM for Oregon (from geofabrik.de) into an FGDB and am doing some routing in downtown Portland with Network Analyst (10.2).  I'm getting some results that I wouldn't expect -- it's doing a U-turn on to a parallel segment of the same (divided) road, even though I have U-Turns at Junctions set to Not Allowed.  I think that Network Analyst is not seeing them as U-turns because they are different segments, and I'll accept that.  But these intersections are also tagged with restriction=only_straight_on.  From what I can tell by looking at the nd_turns, it looks like some turns that are not being imported properly from the OSM data -- specifically those tagged only_straight_on.  I took a look at the code but I'm not really a programmer so I can't tell what's going on.  Can someone explain the logic in how OSM turns are imported into a network dataset?

![hawthornebridge](https://f.cloud.github.com/assets/5050497/2299452/43da87fc-a0cd-11e3-9b92-79c25e5b3121.png)

![westburnside](https://f.cloud.github.com/assets/5050497/2299455/489c6198-a0cd-11e3-8c54-1a59ed49268f.png)

**Comment by paulcone** [comment]
I've noticed lots of work on this project.  Any update on fixing this specific issue?

**Comment by robblis** [comment]
This is being looked at. No, solution yet.

**Comment by ThomasEmge** [comment]
Paul,
I made changes in the code such that your outlined examples won't happen any more and turn restriction are properly build. However you would still need to expand our sample network model to properly handle a very complex Portland situation.

Thomas

**Comment by paulcone** [comment]
Thomas,

Can you explain more what you mean by "a very complex Portland situation"?
How is it complex?

Paul

**Comment by ThomasEmge** [comment]
The challenge arises from the way the OSM data is structured and the way ArcGIS would define a network. Currently each vertex is a junction in the network and not all vertices/junctions have a turning restriction or not all edges have traffic directions defined. 
For example going up Northwest Broadway will eventually result in a U-turn when turn restrictions are no longer present and other roads attributes allow for such a maneuver. 
What I am trying to say to say is that our network definition suggestion called "GenericDrive.xml" doesn't completely model the Portland situation and our network instructions need refinement. 
We are looking for feedback on what is or would be the appropriate model.

**Comment by paulcone** [comment]
Thomas,

I'd like to help more on this.  Can you give me some guidance on what sort of description you need for an appropriate model?

Paul
