### ISSUE TITLE
Toolbox doesn't show up after installation

### ISSUE THREAD

**Issue by rooster611** [Esri/arcgis-osm-editor#44]
I'm running version 10.2.2 of ArcGIS desktop and the installation wizard runs successfully but the toolbox does not show up in the installation folder (C:/Program Files/ESRI/OSMEditor). The only files that appear are in a folder called 'bin', which I've attached in the attached image. I can "add" the toolbox through ArcMap, however it says there is a conflict error when it opens. I've installed the most recent version of the editor (10.2.x) so it shouldn't be a compatibility issue.

Does anybody know what the issue is? I can't figure it out for the life of me. Any help would me much appreciated :)

![osm](https://cloud.githubusercontent.com/assets/7606324/3001773/685dba28-dd35-11e3-8109-c66cd2228bce.PNG)

**Comment by nurulizzahh** [comment]
I know that its too late, but to people who have the same problem, you have to install  ArcGIS editor for your version.  Then, the Openstreetmap toolbox will be available.

**Comment by brunananan** [comment]
> Wow, figured it out. Not my finest moment. I was trying to enable the toolbox through the drop down menu, customize --> toolbars --> OpenStreetMap Toolbox, which doesn't work. I had to add the toolbox by right clicking the arc toolbox and hitting 'add toolbox'.

thx
