### ISSUE TITLE
10.2 - General Function Failure when running OSM Attribute Selector

### ISSUE THREAD

**Issue by eggwhites** [Esri/arcgis-osm-editor#5]
When I run the OSM attribute selector tool on a GDB created through the Load OSM File tool (originating .osm file downloaded from overpass xapi), I get warnings for a "General Function Failure" for various tag values (e.g., barrier, bicycle, tiger fields, etc...). This happens for point, line and polygon layers. I'm using the ALL parameter for which additional tags to extract.

**Comment by OneHwang** [comment]
I encountered this bug as well. It would be nice to have the option to do background geoprocessing so that we could do other things while it's executing in ArcGIS. Can someone at ESRI be assigned to fix this? Thanks.

**Comment by marcos-fedato** [comment]
Form me, this happens when i try to select an attribute that has a ":" symbol on the name, like "addr:suburb". 
Luckly in my case geofabrik.de has a shapefile download and i can do my processing it with the places.shp filtering the features by "type" = 'suburb'.

**Comment by ThomasEmge** [comment]
I added additional checks into the selector tool and this issue should be fixed with the next release.
