### ISSUE TITLE
Crash when loading >4GB *.osm file with Conserve Memory turned off (32-bit geoprocessing)

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#74]
Hi Thomas,

I haven't had the time to verify this further, but wanted to report it anyway.

What I encountered: I have tried to import (Load OSM File) a 9 GB osm file for Australia / Oceania. I have successfully imported this one before, however with "Conserve Memory" checked ***on*** as default since I didn't yet upgrade my PC to 16 GB.

Now, with 16 GB RAM available, and following the rough guideline that the maximum size of the OSM file that can be processed in memory is about equal to RAM, I checked "Conserve Memory" ***off***...

However, I had forgotten I was running 10.2.2 with no 64-bit background processing (as per your recommendation concerning the test dlls), but just 32-bit processing. When I checked the next morning after starting the process, the PC had crashed, I needed to do a full reboot to get it running normally again.

Of course, with 32-bit processing, whether background or foreground, ArcGIS can not address more than about 4 GB memory, so that definitely is a potential cause of issues, and the likely cause of this crash.

Maybe the "Conserve Memory" option needs to be disabled if no 64-bit geoprocessing is enabled, and default to "Conserve Memory" checked on in that case, to avoid such a crash.

Anyway, even with 64-bit geoprocessing, it would be good to avoid such crashes at all, by better handling memory limitations (if that was the cause of my crash, as I wrote, I haven't yet had the opportunity to look into this further). Even with 64-bit geoprocessing, some windows editions like Windows 7 Home Basic and Home Premium edition, can not address more than 8 and 16 GB respectively (https://msdn.microsoft.com/en-us/library/aa366778%28VS.85%29.aspx#physical_memory_limits_windows_7).

I don't know what other checks ESRI could do to prevent crashes, but it may be worth doing a quick check to confirm a potential issue with a not properly catched memory limitation.

You can download a similar file easily from Geofabrik for testing.

**Comment by ThomasEmge** [comment]
Yes, I agree it shouldn't crash the application and the parameter is essentially a leftover from early testing which I considered useful at the time. We should probably take it out.

**Comment by mboeringa** [comment]
> Yes, I agree it shouldn't crash the application and the parameter is essentially a leftover from early testing which I considered useful at the time. We should probably take it out.

\+ 1, removing the option, which is of very limited value, is probably the best solution.
