### ISSUE TITLE
Problem with the "Load OSM file" tool

### ISSUE THREAD

**Issue by tonyemery** [Esri/arcgis-osm-editor#83]
Hello,

When I try to use the "Load OSM file" tool, I receive an error message when trying to loading the data into a feature class game so I ticked the geoprocessing option "Replace results of geoprocessing operations". By the way, the tool works very well when the feature class set does not exist.
Error encountered: "Incompatible version of OSM extension detected (Detected 1, 2 expected).".

**Comment by eggwhites** [comment]
Hello Tony - I was able to replicate the behavior here. I'll continue to look at it tomorrow and see why it's happening.

**Comment by eggwhites** [comment]
I think this is a bug - or if its working as designed, then tool documentation should be updated.  Steps to replicate:
1) Manually create a feature dataset in ArcCatalog, with the following feature classes: 1) a point feature class with the name [nameOfFeatureDataset]_osm_pt, 2) a line feature class with the name [nameOfFeatureDataset]_osm_ln, and a polygon feature class with the name [nameOfFeatureDataset]_osm_ply. Accept the defaults in the wizard for creating the new feature classes.
2) Launch the Load OSM File tool, and attempt to populate the tool such that the .osm file target feature class is this new empty one you've created. 
3) You will get the error described above in the user interface  "Incompatible version of OSM extension detected (Detected 1, 2 expected).", and won't be able to run the tool.

**Comment by eggwhites** [comment]
Further question here - is there a workflow where this issue is critical, versus just being annoying that you have to use the tool to create the feature dataset rather than creating it in advance? If so, will you please describe that workflow? e.g., script or process? Thanks!

**Comment by tonyemery** [comment]
In fact, when I launch the tool alone or in a model builder, it's the same result.
The problem is that I need to relaunch OSM data to have the lastest version of the features. First I tried with the diff OSM Load tool but, even with a small data set, it runs during 2 or 3 days without downloading data.
So I have created a model builder witch use xapi dowload tool, load osm data tool and attribute tool for every data set I need (highway, landuse, leisure, natural, waterway, ...)
And then I made some very beautiful city map with ArcGIS...

**Comment by tonyemery** [comment]
Another problem with this tool.
I made a model builder with this tool and export il in python. When I run the Python script, I get the following error : 
Traceback (most recent call last):
  File "V:\_FMW\Voirie\4-ChargementGDB.py", line 30, in <module>
    arcpy.OSMGPFileLoader_osmtools(voies_osm, "CONSERVE_MEMORY", "ALL", voies, OSM_Points, OSM_Lines, OSM_Polygons)
AttributeError: 'module' object has no attribute 'OSMGPFileLoader_osmtools'

**Comment by tonyemery** [comment]
Hello, could you tell me if you have found any solution with my problem.
The fact is that I have to show this toolbox in the next ESRI France Forum in september but if it doesn't works, I prefer not to show it.

**Comment by ThomasEmge** [comment]
Tony,

if you generate your own toolbox then the name/reference of the loader tool will change. 'arcpy.OSMGPFileLoader_osmtools' is referring to the tool in our toolbox. The nomenclature is name_of_tool__toolbox_alias. If your toolbox uses a different alias then you need to adjust the name accordingly. Also, if your script is running stand-alone, you might need to load the OpenStreetMap toolbox explicitly. For more information take a look at the arcpy help at http://desktop.arcgis.com/en/desktop/latest/analyze/python/adding-and-removing-toolboxes.htm

**Comment by tonyemery** [comment]
Thank you for the answer. 
Have you any solution for the first problem witch was : 
Incompatible OSM extension version detected. (Detected 1, expected 2)

**Comment by ThomasEmge** [comment]
That is pretty much expected behavior and a design choice we made for this release. 

The reasoning was the following:
1. We are no longer adding the OSM custom object behavior by default. The custom behavior is the magic that makes the wonderful OSM editor work but only if you are intending to edit the OSM data. Based on the feedback we received only very few people are actually editing the data so it was more of a nuisance than anything else and hence we removed it. You can still enable the behavior (and you have to for editing) but it is now the additional step of enabling the OSM extension and the "Download, Extract, and Symbolize" model shows you how to do that.
2. We used the OSM extension information to tell what version of the OSM download we are dealing with. A couple releases ago we had a breaking schema change that causes this ripple effect. Now with the extension gone we don't know and decided to show the error you are encountering.
The solution is however fairly simple. Delete the feature dataset (because the tool would do exactly the same thing) and then load the osm file into a feature dataset which happens to have the same name you just deleted.

**Comment by tonyemery** [comment]
Hello everybody,

I'm sorry but I still have problems with my python script.
This is the script (I put "print" to see where the problems come from) : 

print('0.0 Lancement du script de chargement du fichier osm dans la GDB')
print('1.1 Import du module arcpy')
import arcpy
print('1.3 Modules importés')
print('2.1 Définition des arguments ')
file_osm = "V:\\_PROJETS\\_CCPRO_OSM\\OSMFiles\\voies.osm"
Add_OSM_tag_keys_to_schema = "ALL"
layer = "V:\\_GDB\\OSM_CCPRO.gdb\\voies2"
print('2.2 Arguments définis')
print('3.1 Définition des variables ')
layer_osm_pt = file_osm
layer_osm_ln = file_osm
layer_osm_ply = file_osm
print('3.2 Variables définies')
print('4.1 Lancement du process 3LoadFile_One')
arcpy.OSMGPFileLoader_osmtools(file_osm, "CONSERVE_MEMORY", Add_OSM_tag_keys_to_schema, layer, layer_osm_pt, layer_osm_ln, layer_osm_ply)
print('99. script 3LoadFile_One achevé')
________________________________
And this is the result : 

0.0 Lancement du script de chargement du fichier osm dans la GDB
1.1 Import du module arcpy

Warning (from warnings module):
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\__init__.py", line 157
    warnings.warn("Failed importing {0}".format(filename))
UserWarning: Failed importing c:\program files (x86)\arcgis\desktop10.3\ArcToolbox\Toolboxes\ccpro_download_using_xapi.py
0.0 Lancement du script DownloadOSMFiles
1.1 Import des modules arcpy, sys, urllib, urllib2
1.2 Import du module local
1.3 Import des modules arcpy.ImportToolbox

Warning (from warnings module):
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\__init__.py", line 157
    warnings.warn("Failed importing {0}".format(filename))
UserWarning: Failed importing c:\program files (x86)\arcgis\desktop10.3\ArcToolbox\Toolboxes\DownloadOSMFiles.py

Warning (from warnings module):
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\__init__.py", line 157
    warnings.warn("Failed importing {0}".format(filename))
UserWarning: Failed importing c:\program files (x86)\arcgis\desktop10.3\ArcToolbox\Toolboxes\download_using_xapi.py

Warning (from warnings module):
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcPy\arcpy\__init__.py", line 157
    warnings.warn("Failed importing {0}".format(filename))
UserWarning: Failed importing c:\program files (x86)\arcgis\desktop10.3\ArcToolbox\Toolboxes\LoadFiles.py
1.3 Modules importÃ©s
2.1 DÃ©finition des arguments 
2.2 Arguments dÃ©finis
3.1 DÃ©finition des variables 
3.2 Variables dÃ©finies
4.1 Lancement du process 3LoadFile_One

Traceback (most recent call last):
  File "V:\_ARCGIS\3LoadFile_One.py", line 34, in <module>
    arcpy.OSMGPFileLoader_osmtools(file_osm, "CONSERVE_MEMORY", Add_OSM_tag_keys_to_schema, layer, layer_osm_pt, layer_osm_ln, layer_osm_ply)
AttributeError: 'module' object has no attribute 'OSMGPFileLoader_osmtools'

**Comment by tonyemery** [comment]
I see where is the problem. It's the UTF-8 encoding option of Python Shell...
