### ISSUE TITLE
Working with geofabrik regional exports

### ISSUE THREAD

**Issue by aparisien** [Esri/arcgis-osm-editor#88]
Has anyone run across an issue with importing regional (I'm talking South America as a whole) extracts from Geofabrik?  I can load it (using Load OSM File tool from OpenStreetMap Toolbox) but there are no road/city/town/river/etc names in the features.

Is this something that geofabrik removes from these extracts?  Is there a way that I can add them back in?
I'm trying to make a basemap using osm data and having the names is a requirement to making the map functional.  When I extract a small area directly from OSM.org I get all of the attributes.  Is this a Geofabrik issue or an arcGIS issue?

Any help appreciated

**Comment by mboeringa** [comment]
What tool do you use to extract a "small area directly", where you do get the names?

Normally, when you use the **Load OSM File** tool to load an extract from Geofabrik, you get just a limited set of the major attributes fields, that does **not** include include the OSM "name" key / field.

To get it, you need to use the **OSM Attribute Selector** and enter "name" as the key to extract.

As you may not know, ESRI actually stores *all* key/value tags on any object in the Feature Classes attribute table inside a special binary field. This is a key/value storage equivalent to HStore in PostGresql. You can not access the data in there directly, but the **OSM Attribute Selector** allows you to extract a specific key from this key/value storage and add it as an attribute to the attribute table of the Feature Class.
