### ISSUE TITLE
Change Editor to use the Changeset Diff Upload

### ISSUE THREAD

**Issue by ajturner** [Esri/arcgis-osm-editor#89]
Change from using the [Element API](http://wiki.openstreetmap.org/wiki/API_v0.6#Create:_PUT_.2Fapi.2F0.6.2F.5Bnode.7Cway.7Crelation.5D.2Fcreate)  to instead use the [Changeset Diff Upload](http://wiki.openstreetmap.org/wiki/API_v0.6#Diff_upload:_POST_.2Fapi.2F0.6.2Fchangeset.2F.23id.2Fupload)

Per @pnorman at SOTMUS 2015 the single Element is not preferred and likely will be going away in the future

**Comment by pnorman** [comment]
The future is not going to be the immediate future, but the diff upload should be faster with fewer individual requests as well as more resilient in cases of interrupted connections.

**Comment by ThomasEmge** [comment]
This functionality is already implemented under the "Bundle Data Upload(s)" parameter for the uploader geoprocessing tool. It should be the recommended way to upload local edits. If you run into upload error the user can uncheck the option so the conflict resolution editor can detect and address the potential versioning issues.
