### ISSUE TITLE
Unclosed way with tags set to osmSupportingElement = yes

### ISSUE THREAD

**Issue by mboeringa** [Esri/arcgis-osm-editor#90]
I am seeing an issue with an import that I can't yet explain. In a recent import of Austria, I see an unclosed way with a tag of **waterway = river** that is set to osmSupportingElement = yes, despite having the tag of its own. The way is also part of two multipolygon relations in the role of "outer", but should be an object on its own considering the valid tag.

See the attached images:
![arcgis_missing_way](https://cloud.githubusercontent.com/assets/7635726/8340844/721bd570-1ac1-11e5-9c76-e010ccc8fa87.jpg)
![openstreetmap_website_missing_way1](https://cloud.githubusercontent.com/assets/7635726/8340845/721e3bc6-1ac1-11e5-9d87-1781a38910c2.jpg)
![openstreetmap_website_missing_way2](https://cloud.githubusercontent.com/assets/7635726/8340846/72207544-1ac1-11e5-8d37-4b2409cb9365.jpg)

**Comment by ThomasEmge** [comment]
Nice catch. Fixed for the next release.

**Comment by mboeringa** [comment]
@ThomasEmge,

I don't know how long it will take to release the next version of the tool, however, considering there is a small wishlist, I guess this may take some time...

Because of this, I was wondering if it would be possible to release a minor "bug-fix" version, that only includes a fix for this particular issue. I have now encountered more examples of what I assume is the same issue, with in this case ways representing roads. See the image below from Rome, Italy (the two missing ways marked by the right arrows near Castle St Angelo are OSMID 122081879 and OSMID 32455055).

Considering "loosing" ways is always a pretty major issue, and, depending on how the **Create OSM Network Dataset** uses the data and if it uses or considers the **osmSupportingElement=yes/no** tag, may also signficantly affect the ability to create a routable network (I haven't used the tool up to now, so can't tell), it might really be desirable to see this fixed in a minor release of the toolbox, including backported to all currently supported versions of ArcGIS (>= 10.2.1, wasn't it?).

![arcgis_missing_ways_rome](https://cloud.githubusercontent.com/assets/7635726/11222800/ea65859e-8d6c-11e5-9b4e-ee06bb1db5a5.png)

**Comment by mboeringa** [comment]
@ThomasEmge , I still wait for the Italy import to finish, but I wanted to share some results for the latest DLLs for an import of Spain. This is in Barcelona. 

Notice that in the top image, before the fix, almost the entire length of the "Avinguda del parallel" (orange road) is missing, and also note the missing road segments in entire right of image, near the Museu Maritim, e.g. near the roundabout. Their are other clearly missing roads as well, e.g. see the road just below the Caixaforum Barcelona building on the left.

The second image is from the new DLLs with the fix. Notice that road pattern looks much better, and no obvious missing roads.

As I stated before, I think it would be desirable to have this particular fix backported to all currently supported versions of the tool, and maybe even released before a final new version of toolbox with additional functionality, as it is a pretty major issue missing these roads.

![arcgis_missing_ways_barcelona_old](https://cloud.githubusercontent.com/assets/7635726/11607514/d79cf16e-9b49-11e5-8e6f-6d3e56553cd5.png)

![arcgis_missing_ways_barcelona_new](https://cloud.githubusercontent.com/assets/7635726/11607515/df392618-9b49-11e5-888a-fd4f0a59edcf.png)

**Comment by mboeringa** [comment]
OK, the new Italy import and rendering session finished as well, so although it was already clear from the above image that the issue was fixed, I hereby post an image of the Castle St. Angelo in Rome as extra confirmation. Looks good.

![arcgis_missing_ways_rome_new](https://cloud.githubusercontent.com/assets/7635726/11612813/bd0a33c4-9c08-11e5-9343-24c56b0ecbe2.png)
