### ISSUE TITLE
add toolbox

### ISSUE THREAD

**Issue by antoine84** [Esri/arcgis-osm-editor#91]
Hello, i am Antoine,
excuse me for my bad English.
I installed the osm editor 10.3 for my toolbox of ArcMap 10.3 but it did not add to my other toolbox. I do not know how to manually add it too. What can I do to install it properly and so I use it? Thank you

**Comment by robblis** [comment]
Hi Antoine,

Once the OSM Editor is installed, you should see a toolbox named OpenStreetMap Toolbox under the System Toolboxes folder in ArcMap.

**Comment by antoine84** [comment]
hello , thank you for the answer. When I open the ArcMap, the toolbox was not added automatically. it is not available . I'll get to where the toolbox system folder is located.

**Comment by antoine84** [comment]
it's ok for me i find the toolbox :D thank you

**Comment by pshowalter** [comment]
I had same issue with the OSM Toolbox not being added to the System tool box.  This was with 10.2.2 and 10.3.1.

**Comment by acartas** [comment]
What is the solution to this? I have a successful install as well but don't know where to find the toolbox.

**Comment by robblis** [comment]
Both the 32 bit and 64 bit installers will deploy the OSM toolbox to the <ArcGIS Desktop Install directory>\ArcToolbox\Toolboxes directory. With the 64 bit installer if you don't have the Desktop Background Geoprocessing (64 bit) installed, the 64 bit assemblies won't be deployed.

In either case, the toolbox files should be deployed providing your user credentials have administrator rights on the machine. Make sure ArcMap and/or ArcCatalog is not running during installation. After installation if you don't see the OpenStreetMap Toolbox under System Toolboxes, check the <ArcGIS Desktop Install directory>\ArcToolbox\Toolboxes directory to see if the OpenStreetMap Toolbox.tbx file exists. If it doesn't exist, then there is probably a permissions issue writing to that folder. Verify you have write access by creating a text file in the folder.

**Comment by pshowalter** [comment]
When installed, its **not** in the default Toolbox that opens when clicking on the Toolbox icon on the Main menu.  Use the Catalog window to scroll to System Toolbox.
![image](https://cloud.githubusercontent.com/assets/6842145/9740011/8e7faecc-5620-11e5-982d-64f712a9f91d.png)

![image](https://cloud.githubusercontent.com/assets/6842145/9740034/b86cf398-5620-11e5-96dc-7164d14c546c.png)
