### ISSUE TITLE
ArcMap network based on Open Streetmap data

### ISSUE THREAD

**Issue by tzimmer2** [Esri/arcgis-osm-editor#95]
Hello all,
 
I would like to build a multimodal network for several regions in Chile in order to calculate distances for train and truck transportation between cities. I have completed the Network Analyst tutorial and played around a bit with the ArcGIS Editor for OSM.
 
Is there a way to download only certain features from OSM using the ArcGIS Editor? The Download, Extract & Symbolize Tool seems to convert the whole content of the chosen area to features which limits the extent of data downloaded. Instead of downloading every feature for a small area I would like to download only the street or railway features for the whole region.
 
One more thing ... I have found shapefiles representing only the road and railway network in Chile. However, roads are not always connected in the shapefile and when I create a network from it without any preparation I cannot find routes for longer distances due to these gaps. I guess that I would need to use the integration tool before building the network. But since the OSM data seems to work very well I wanted to try that first. Thank you.

**Comment by ThomasEmge** [comment]
Excellent questions. There are a number of ways of achieving your workflow. Depending on your geographical area you could try the XAPI downloader as it allows you to define predicates to streamline your download request. For more information please take a look at http://wiki.openstreetmap.org/wiki/Xapi

The other approach would be to download the OSM file for Chile from http://download.geofabrik.de/south-america.html and then use osmosis to create a subset of the elements you are interested in. For osmosis please take a look at this link http://wiki.openstreetmap.org/wiki/Osmosis

The third approach would be to load all of Chile for data exploration and then make a decision on the geometries and features you need to build out your network.

Yes connectedness will be an issue and might require some integration work before building the network.

**Comment by tzimmer2** [comment]
Thank you very much for your answer. The XAPI downloader was exactly what I was looking for.

Besides, I found another website I would like to mention here. Trimble (https://market.trimbledata.com) also allows downloading single features for a given region.
