### ISSUE TITLE
Empty revision tables version 10.3.1

### ISSUE THREAD

**Issue by peedest** [Esri/arcgis-osm-editor#97]
successfully using tools to download OSM data, perform edits. Revision table stays empty though, so no upload of edits to OSM possible. Have installed latest OSM editor and latest ArcGIS version 10.3.1.

Could be user error (first time using the tools), but similar behaviour experienced by one of our partners - they have been able to revert to 10.2 and the tool works fine....

**Comment by peedest** [comment]
User error! Tool working OK

**Comment by mhogeweg** [comment]
Brilliant!

**Comment by peedest** [comment]
well Marten I think so, my revision tables now have content, but they do seem to be taking a long time to show up in the OSM database

**Comment by mhogeweg** [comment]
@robblis

**Comment by ThomasEmge** [comment]
What is a long time? On average I believe you should see the updates within 15 minutes. If the server is busy and has a lot of other rendering requests queued up, then it might take longer.

**Comment by peedest** [comment]
http://www.openstreetmap.org/api/0.6/changeset/34493258 - submitted 2 days ago via ArcGIS OSM editor, still no features showing in OSM (revision table was checked and had the features in it)....

**Comment by peedest** [comment]
OK I think I understand the problem. OSM download gives you three feature types - point, line, poly. To be able to upload features you have to "Add OSM Editor Extension", where you have to select the input OSM Feature Layer (of which there are three possible choices). I had selected all three, one by one, but I suspect the only active one is the last one you choose. I just ran a test and made sure I only selected the "name_osm_ln" feature layer, and I got not only a populated revision table, but also a results message that 12 features uploaded and a refresh of my OSM web client showed these features within 5 minutes on the server.........

**Comment by peedest** [comment]
Are there any issues when returning to edit an OSM Feature Layer, i.e. edits done, uploaded, then add new features to the same feature layer? I get a "Unable to save edits. Cannot acquire a lock" error.....

**Comment by ThomasEmge** [comment]
No, there shouldn't be an issue. It could be that another instance of ArcMap or ArcCatalog or some other desktop application established an exclusive write lock and when using a file geodatabase then there is only one process allowed to write data.
