### ISSUE TITLE
Errors in installing ArcGIS Editor for OSM

### ISSUE THREAD

**Issue by xenia99** [Esri/arcgis-osm-editor#99]
I want to use OSM data to make network dataset in ArcGIS 10.2.2 However, this is not installed successfully. It keeps telling me I don't have ArcGIS 10.2.2 that is exactly what I am using now. I think others have same issues. Anyone help me to resolve this problem? 

Further information for this issue, I am using 10.2.2 desktop with 64 bit. And this is concurrent user version supported by my school for the researcher. I can use all of functions and extensions with this privilege. Also, I followed the direction indicated below: http://www.arcgis.com/home/item.html?id=16970017f81349548d0a9eead0ebba39

As you can see comments in the website, other people have same issues like me. Please help me out!

**Comment by robblis** [comment]
Please make sure you are administrator on the machine. You can try to right click on the setup.exe and select Run as administrator.

If the install process still gives a warning about not finding 10.2.2, double check your ArcMap version in Programs and Features and make sure the version number is 10.2.3552. Verify you can read and write to the windows registry with the user installing the application.

**Comment by xenia99** [comment]
Thanks for your suggestions. I did double check, and found the version is 10.2.0.3348.
In this case, how can I solve this problem? I am administrator on this machine and can read and write the registry.

Thanks!

**Comment by robblis** [comment]
10.2.0.3348 indicates that ArcGIS 10.2 for Desktop is currently on the system.

The ArcGIS Editor for OSM 10.2.x needs ArcGIS for Desktop 10.2.1 or 10.2.2 installed.

Please check your system and make sure you've installed 10.2.1 or 10.2.2.

The name and version in the Programs and Features should read:
ArcGIS 10.2.1 for Desktop          (Version column) 10.2.3497
or
ArcGIS 10.2.2 for Desktop          (Version column) 10.2.3552

**Comment by xenia99** [comment]
I've checked the name and version in the Programs and Features.
It is ArcGIS 10.2 for Desktop and 10.2.3348
![picture1](https://cloud.githubusercontent.com/assets/15041040/10401499/60e7d23e-6e8d-11e5-8cd1-8e36a0f6d2a2.png)

Please help me out. 
Thanks!

**Comment by eggwhites** [comment]
Hello - Thanks for bringing this up. In short, the "10.2.x" installer will not work on 10.2.0, and we do not have a released installer for 10.2.0 because there were issues that we fixed in our 10.2.1 release.  I will update the documentation to be clear on this. It is different for our 10.3 installer - it works on 10.3 and 10.3.1.  

Is it possible for you to upgrade to 10.2.1? If absolutely not, we might be able to get you a 10.2.0 version but the 10.2.1 is better.

**Comment by xenia99** [comment]
Thank you so much! I will try to upgrade it to 10.3.

**Comment by eggwhites** [comment]
Very good - please note, if you move to 10.3, use the installer available here: http://www.arcgis.com/home/item.html?id=75716d933f1c40a784243198e0dc11a1

**Comment by xenia99** [comment]
I succeeded to upgrade to 10.3 and it works!

However, I have other issues 1) downloading osm file by using 'Download OSM Data (XAPI), 2) loading osm file (which is downloaded directly from OpenStreetMap by using QGIS because 'Download OSM Data (XAPI) doesn't work). 

Please see below:

1. In downloading osm data by using 'Download OSM Data (XAPI), I faced this error message.

Executing: XAPIDownload http://jxapi.openstreetmap.org/xapi/api/0.6/ "-77.3976291149929 38.738358718205 -76.955366062459 38.9737093448305" * # C:\Users\cl8ax\Desktop\test.osm
Start Time: Fri Oct 09 16:03:20 2015
Running script XAPIDownload...
-77.3976291149929 38.738358718205 -76.955366062459 38.9737093448305
http://jxapi.openstreetmap.org/xapi/api/0.6/*%5Bbbox%3D-77.397629115%2C38.7383587182%2C-76.9553660625%2C38.9737093448%5D
Unable to reach the server.
Completed script XAPIDownload...
Failed to execute (XAPIDownload).
Failed at Fri Oct 09 16:03:42 2015 (Elapsed Time: 21.46 seconds)

2. Because of above failure, I tried to download osm file by using QGIS and load it to ArcMap by using 'Load OSM file'. I faced this error message.

Executing: OSMGPFileLoader C:\Users\cl8ax\Desktop\I-495.osm CONSERVE_MEMORY # C:\Users\cl8ax\Documents\ArcGIS\Default.gdb\I-495 C:\Users\cl8ax\Documents\ArcGIS\Default.gdb\I-495\I-495_osm_pt C:\Users\cl8ax\Documents\ArcGIS\Default.gdb\I-495\I-495_osm_ln C:\Users\cl8ax\Documents\ArcGIS\Default.gdb\I-495\I-495_osm_ply
Start Time: Fri Oct 09 15:54:06 2015
Counting elements in OSM file...
Counted 4548085 nodes, 498474 ways, and 4354 relations.
Preparing geodatabase...
The table name is invalid.
   at ESRI.ArcGIS.Geodatabase.IFeatureWorkspace.CreateFeatureDataset(String Name, ISpatialReference SpatialReference)
   at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPFileLoader.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
Failed to execute (OSMGPFileLoader).
Failed at Fri Oct 09 15:56:39 2015 (Elapsed Time: 2 minutes 33 seconds)

Could anyone help me resolve either of two errors?

Thanks!

**Comment by scw** [comment]
It looks like the XAPI URL is pointing to a service that is no longer running (issue #85) -- try changing the XAPI URL to `http://www.overpass-api.de/api/xapi_meta?` and see if it resolves your issue. There are other [services available](http://wiki.openstreetmap.org/wiki/Xapi#Web_services_available) as well, if that one also causes issues.

**Comment by ThomasEmge** [comment]
The second error is because "I-495" is not a valid name for feature dataset. This should be flagged as an error before you even execute the tool. Looks like a bug. Please drop the dash and change the name to something like "I495" and it will work.

I think though the tool are looking for is "Download OSM Data". Using this tool you can use the ArcMap view as the download extent for the OSM data.
Here is the kind of recommended order of tools in terms of allowable download size:
1. Download OSM Data  - the OSM server will you when you are requesting too much data
2. Download OSM Data (XAPI) - these download URLs are providing larger download sizes but the data might be 1 or 2 days behind the OSM master server.
3. OSM File Loader - no limit on the size but you need to get the OSM file yourself from something like http://download.geofabrik.de

**Comment by xenia99** [comment]
Thank you so much!
But I still have same issue with a changed name "495". Please give me any suggestions.

Executing: OSMGPFileLoader C:\Users\cj\Desktop\OSM\495\495.osm CONSERVE_MEMORY # C:\Users\cj\Documents\ArcGIS\Default.gdb\495 C:\Users\cj\Documents\ArcGIS\Default.gdb\495\495_osm_pt C:\Users\cj\Documents\ArcGIS\Default.gdb\495\495_osm_ln C:\Users\cj\Documents\ArcGIS\Default.gdb\495\495_osm_ply
Start Time: Mon Oct 12 02:59:29 2015
Counting elements in OSM file...
Counted 4548085 nodes, 498474 ways, and 4354 relations.
Preparing geodatabase...
The table name is invalid.
   at ESRI.ArcGIS.Geodatabase.IFeatureWorkspace.CreateFeatureDataset(String Name, ISpatialReference SpatialReference)
   at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPFileLoader.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
Failed to execute (OSMGPFileLoader).
Failed at Mon Oct 12 03:00:33 2015 (Elapsed Time: 1 minutes 4 seconds)

**Comment by pshowalter** [comment]
Additional rules

*  Names must begin with a letter, **not a number** or special character such as an asterisk (*) or percent sign (%). 
* Names should not contain spaces. If you have a two-part name for your table or feature class, connect the words with an underscore (_), for example, garbage_routes. 
* Names should not contain reserved words, such as select or add. Consult your DBMS documentation for additional reserved words. 
* The length of feature class and table names depends on the underlying database. The maximum name length for file geodatabase feature classes is 160 characters. Be sure to consult your DBMS documentation for maximum name lengths.
